package com.sivion.api.crm.domain;
import jakarta.persistence.*; import java.math.BigDecimal; import java.time.Instant;
@Entity @Table(name="crm_opportunities") public class Opportunity {
 @Id @GeneratedValue(strategy=GenerationType.IDENTITY) Long id; @Column(name="tenant_id",nullable=false) Long tenantId; @Column(nullable=false,length=40) String opportunityNumber;
 @Column(nullable=false,length=200) String name; @Column(name="customer_id") Long customerId; @Column(name="lead_id") Long leadId; @Column(length=40,nullable=false) String stage="QUALIFICATION"; @Column(precision=18,scale=4) BigDecimal amount;
 @Column(name="probability",precision=5,scale=2) BigDecimal probability=BigDecimal.ZERO; @Column(name="expected_close_date") java.time.LocalDate expectedCloseDate; @Column(name="assigned_to",length=200) String assignedTo;
 @Column(length=1000) String description; @Column(name="created_at",nullable=false) Instant createdAt; @Column(name="updated_at",nullable=false) Instant updatedAt;
 @PrePersist void p(){createdAt=Instant.now();updatedAt=createdAt;} @PreUpdate void u(){updatedAt=Instant.now();}
 public Long getId(){return id;} public Long getTenantId(){return tenantId;} public void setTenantId(Long v){tenantId=v;} public String getOpportunityNumber(){return opportunityNumber;} public void setOpportunityNumber(String v){opportunityNumber=v;} public String getName(){return name;} public void setName(String v){name=v;} public Long getCustomerId(){return customerId;} public void setCustomerId(Long v){customerId=v;} public Long getLeadId(){return leadId;} public void setLeadId(Long v){leadId=v;} public String getStage(){return stage;} public void setStage(String v){stage=v;} public BigDecimal getAmount(){return amount;} public void setAmount(BigDecimal v){amount=v;} public BigDecimal getProbability(){return probability;} public void setProbability(BigDecimal v){probability=v;} public java.time.LocalDate getExpectedCloseDate(){return expectedCloseDate;} public void setExpectedCloseDate(java.time.LocalDate v){expectedCloseDate=v;} public String getAssignedTo(){return assignedTo;} public void setAssignedTo(String v){assignedTo=v;} public String getDescription(){return description;} public void setDescription(String v){description=v;}
}
