import {Injectable,inject} from '@angular/core';
import {HttpClient,HttpHeaders} from '@angular/common/http';
import {firstValueFrom} from 'rxjs';
export interface Employee {id?:number; employeeNumber:string; firstName:string; lastName:string; email:string; phone?:string; departmentId?:number; designation?:string; managerId?:number; joiningDate?:string; status?:string;}
export interface Department {id?:number; code:string; name:string; parentId?:number; status?:string;}
export interface Attendance {id?:number; employeeId:number; attendanceDate:string; status:string; checkIn?:string; checkOut?:string;}
export interface LeaveRequest {id?:number; employeeId:number; leaveType:string; startDate:string; endDate:string; status?:string; reason?:string;}
export interface Goal {id?:number; employeeId:number; title:string; description?:string; targetValue?:number; currentValue?:number; dueDate?:string; status?:string;}
@Injectable({providedIn:'root'}) export class HrApi {private http=inject(HttpClient); private h(){return new HttpHeaders({'X-Tenant-ID':'1'});} employees(){return firstValueFrom(this.http.get<Employee[]>('/api/v1/hr/employees',{headers:this.h()}));} departments(){return firstValueFrom(this.http.get<Department[]>('/api/v1/hr/departments',{headers:this.h()}));} createEmployee(e:Employee){return firstValueFrom(this.http.post<Employee>('/api/v1/hr/employees',e,{headers:this.h()}));} createDepartment(d:Department){return firstValueFrom(this.http.post<Department>('/api/v1/hr/departments',d,{headers:this.h()}));} attendance(){return firstValueFrom(this.http.get<Attendance[]>('/api/v1/hr/attendance',{headers:this.h()}));} markAttendance(a:Attendance){return firstValueFrom(this.http.post<Attendance>('/api/v1/hr/attendance',a,{headers:this.h()}));} leaves(){return firstValueFrom(this.http.get<LeaveRequest[]>('/api/v1/hr/leaves',{headers:this.h()}));} requestLeave(l:LeaveRequest){return firstValueFrom(this.http.post<LeaveRequest>('/api/v1/hr/leaves',l,{headers:this.h()}));} updateLeave(id:number,status:string){return firstValueFrom(this.http.patch<LeaveRequest>(`/api/v1/hr/leaves/${id}?status=${status}`,{}, {headers:this.h()}));} goals(){return firstValueFrom(this.http.get<Goal[]>('/api/v1/hr/goals',{headers:this.h()}));} createGoal(g:Goal){return firstValueFrom(this.http.post<Goal>('/api/v1/hr/goals',g,{headers:this.h()}));}}
