import {Component,OnInit,Input,inject} from '@angular/core'; import {CommonModule} from '@angular/common'; import {FormsModule} from '@angular/forms'; import {HrApi,Employee,Department,Attendance,LeaveRequest,Goal} from './hr-api.service';
@Component({selector:'app-hr',standalone:true,imports:[CommonModule,FormsModule],template:`
<section class="panel"><div class="toolbar"><div><h2>People & HR</h2><p>Employees, organization, attendance, leave and goals.</p></div><button *ngIf="section==='employees'" (click)="newEmployee=true">+ Employee</button><button *ngIf="section==='organization'" (click)="newDepartment=true">+ Department</button></div>
<div class="cards"><article><span>Employees</span><strong>{{employees.length}}</strong><small>People in tenant</small></article><article><span>Departments</span><strong>{{departments.length}}</strong><small>Organization units</small></article><article><span>Pending leave</span><strong>{{pendingLeaves}}</strong><small>Requests awaiting action</small></article><article><span>Goals</span><strong>{{goals.length}}</strong><small>Tracked objectives</small></article></div>
<div *ngIf="section==='employees'"><div class="toolbar"><h2>Employee directory</h2></div><table><thead><tr><th>Number</th><th>Name</th><th>Email</th><th>Department</th><th>Designation</th><th>Status</th></tr></thead><tbody><tr *ngFor="let e of employees"><td>{{e.employeeNumber}}</td><td><b>{{e.firstName}} {{e.lastName}}</b></td><td>{{e.email}}</td><td>{{departmentName(e.departmentId)}}</td><td>{{e.designation||'—'}}</td><td><span class="pill">{{e.status}}</span></td></tr></tbody></table></div>
<div *ngIf="section==='organization'"><div class="toolbar"><h2>Organization structure</h2></div><table><thead><tr><th>Code</th><th>Department</th><th>Parent</th><th>Status</th><th>Employees</th></tr></thead><tbody><tr *ngFor="let d of departments"><td>{{d.code}}</td><td><b>{{d.name}}</b></td><td>{{departmentName(d.parentId)}}</td><td>{{d.status||'ACTIVE'}}</td><td>{{employeesInDepartment(d.id)}}</td></tr></tbody></table></div>
<div *ngIf="section==='attendance'"><div class="toolbar"><h2>Attendance</h2></div><table><thead><tr><th>Date</th><th>Employee ID</th><th>Status</th><th>Check in</th><th>Check out</th></tr></thead><tbody><tr *ngFor="let a of attendance"><td>{{a.attendanceDate}}</td><td>{{a.employeeId}}</td><td>{{a.status}}</td><td>{{a.checkIn||'—'}}</td><td>{{a.checkOut||'—'}}</td></tr></tbody></table></div>
<div *ngIf="section==='leaves'"><div class="toolbar"><h2>Leave management</h2></div><table><thead><tr><th>Employee</th><th>Type</th><th>Dates</th><th>Status</th><th>Action</th></tr></thead><tbody><tr *ngFor="let l of leaves"><td>{{employeeName(l.employeeId)}}</td><td>{{l.leaveType}}</td><td>{{l.startDate}} → {{l.endDate}}</td><td>{{l.status}}</td><td><button *ngIf="l.status==='PENDING'" (click)="approve(l)">Approve</button></td></tr></tbody></table></div>
<div *ngIf="section==='goals'"><div class="toolbar"><h2>Goals</h2></div><table><thead><tr><th>Employee</th><th>Goal</th><th>Progress</th><th>Due</th></tr></thead><tbody><tr *ngFor="let g of goals"><td>{{employeeName(g.employeeId)}}</td><td><b>{{g.title}}</b><br><small>{{g.description}}</small></td><td>{{g.currentValue||0}} / {{g.targetValue||0}}</td><td>{{g.dueDate||'—'}}</td></tr></tbody></table></div>
<div *ngIf="section==='reports'" class="feature-list"><div><strong>Workforce</strong><span>{{employees.length}} employees across {{departments.length}} departments; {{activeEmployees}} active.</span></div><div><strong>Leave</strong><span>{{pendingLeaves}} leave requests currently require approval.</span></div><div><strong>Attendance</strong><span>{{attendance.length}} attendance records loaded for the current reporting window.</span></div><div><strong>Goals</strong><span>{{goals.length}} objectives are currently tracked.</span></div></div>
<div *ngIf="['holidays','meetings','performance','knowledge','documents'].includes(section)" class="feature-list"><div><strong>{{sectionTitle}}</strong><span>The HR workspace is now wired to this section. Its dedicated domain model and lifecycle are the next HR expansion point; the shared role-aware shell and authorization boundary are already in place.</span></div></div>
<div *ngIf="newEmployee" class="modal"><form (ngSubmit)="saveEmployee()"><h2>New employee</h2><input required placeholder="Employee number" [(ngModel)]="draft.employeeNumber" name="number"><input required placeholder="First name" [(ngModel)]="draft.firstName" name="first"><input required placeholder="Last name" [(ngModel)]="draft.lastName" name="last"><input required type="email" placeholder="Email" [(ngModel)]="draft.email" name="email"><select [(ngModel)]="draft.departmentId" name="department"><option [ngValue]="undefined">No department</option><option *ngFor="let d of departments" [ngValue]="d.id">{{d.name}}</option></select><input placeholder="Designation" [(ngModel)]="draft.designation" name="designation"><div class="actions"><button type="button" (click)="newEmployee=false">Cancel</button><button type="submit">Create</button></div></form></div>
<div *ngIf="newDepartment" class="modal"><form (ngSubmit)="saveDepartment()"><h2>New department</h2><input required placeholder="Department code" [(ngModel)]="departmentDraft.code" name="code"><input required placeholder="Department name" [(ngModel)]="departmentDraft.name" name="name"><select [(ngModel)]="departmentDraft.parentId" name="parent"><option [ngValue]="undefined">No parent</option><option *ngFor="let d of departments" [ngValue]="d.id">{{d.name}}</option></select><div class="actions"><button type="button" (click)="newDepartment=false">Cancel</button><button type="submit">Create</button></div></form></div></section>`})
export class HrComponent implements OnInit { @Input() section='employees'; api=inject(HrApi); employees:Employee[]=[]; departments:Department[]=[]; attendance:Attendance[]=[]; leaves:LeaveRequest[]=[]; goals:Goal[]=[]; newEmployee=false; newDepartment=false; draft:Employee={employeeNumber:'',firstName:'',lastName:'',email:'',status:'ACTIVE'}; departmentDraft:Department={code:'',name:'',status:'ACTIVE'}; async ngOnInit(){await this.reload();} async reload(){[this.employees,this.departments,this.attendance,this.leaves,this.goals]=await Promise.all([this.api.employees(),this.api.departments(),this.api.attendance(),this.api.leaves(),this.api.goals()]);} get pendingLeaves(){return this.leaves.filter(x=>x.status==='PENDING').length;} get activeEmployees(){return this.employees.filter(x=>x.status==='ACTIVE').length;} get sectionTitle(){return this.section[0].toUpperCase()+this.section.slice(1);} departmentName(id?:number){return id?this.departments.find(x=>x.id===id)?.name||`Department #${id}`:'—';} employeeName(id:number){const e=this.employees.find(x=>x.id===id);return e?`${e.firstName} ${e.lastName}`:`Employee #${id}`;} employeesInDepartment(id?:number){return this.employees.filter(x=>x.departmentId===id).length;} async saveEmployee(){await this.api.createEmployee(this.draft);this.newEmployee=false;this.draft={employeeNumber:'',firstName:'',lastName:'',email:'',status:'ACTIVE'};await this.reload();} async saveDepartment(){await this.api.createDepartment(this.departmentDraft);this.newDepartment=false;this.departmentDraft={code:'',name:'',status:'ACTIVE'};await this.reload();} async approve(l:LeaveRequest){if(l.id){await this.api.updateLeave(l.id,'APPROVED');await this.reload();}}}
