import {Component,OnInit,Input,inject} from '@angular/core'; import {CommonModule} from '@angular/common'; import {FormsModule} from '@angular/forms'; import {HrApi,Employee,Department,Designation,Attendance,LeaveRequest,Goal} from './hr-api.service';
@Component({selector:'app-hr',standalone:true,imports:[CommonModule,FormsModule],template:`
<section class="panel"><div class="toolbar"><div><h2>People & HR</h2><p>Employees, organization, attendance, leave and goals.</p></div><button *ngIf="section==='employees'" (click)="openNewEmployee()">+ Employee</button><button *ngIf="section==='organization'" (click)="openNewDepartment()">+ Department</button><button *ngIf="section==='organization'" (click)="openNewDesignation()">+ Designation</button></div>
<div class="cards"><article><span>Employees</span><strong>{{employees.length}}</strong><small>People in tenant</small></article><article><span>Departments</span><strong>{{departments.length}}</strong><small>Organization units</small></article><article><span>Designations</span><strong>{{designations.length}}</strong><small>Job titles</small></article><article><span>Pending leave</span><strong>{{pendingLeaves}}</strong><small>Requests awaiting action</small></article><article><span>Goals</span><strong>{{goals.length}}</strong><small>Tracked objectives</small></article></div>
<div *ngIf="section==='employees'"><div class="toolbar"><h2>Employee directory</h2></div><table><thead><tr><th>Number</th><th>Name</th><th>Email</th><th>Department</th><th>Designation</th><th>Status</th></tr></thead><tbody><tr *ngFor="let e of employees"><td>{{e.employeeNumber}}</td><td><b>{{e.firstName}} {{e.lastName}}</b></td><td>{{e.email}}</td><td>{{departmentName(e.departmentId)}}</td><td>{{e.designation||'—'}}</td><td><span class="pill">{{e.status}}</span></td></tr></tbody></table></div>
<div *ngIf="section==='organization'">
<div class="toolbar"><div><h2>Organization structure</h2><p>Manage departments, reporting hierarchy and designations.</p></div></div>
<div class="toolbar"><button type="button" [class.active]="organizationView==='departments'" (click)="organizationView='departments'">Departments</button><button type="button" [class.active]="organizationView==='designations'" (click)="organizationView='designations'">Designations</button></div>
<div *ngIf="organizationView==='departments'"><table><thead><tr><th>Code</th><th>Department</th><th>Parent</th><th>Status</th><th>Employees</th><th>Actions</th></tr></thead><tbody><tr *ngFor="let d of departments"><td>{{d.code}}</td><td><b>{{d.name}}</b></td><td>{{departmentName(d.parentId)}}</td><td><span class="pill">{{d.status||'ACTIVE'}}</span></td><td>{{employeesInDepartment(d.id)}}</td><td><button type="button" (click)="openEditDepartment(d)">Edit</button></td></tr><tr *ngIf="departments.length===0"><td colspan="6">No departments configured yet.</td></tr></tbody></table></div>
<div *ngIf="organizationView==='designations'"><table><thead><tr><th>Code</th><th>Designation</th><th>Department</th><th>Description</th><th>Status</th><th>Actions</th></tr></thead><tbody><tr *ngFor="let d of designations"><td>{{d.code}}</td><td><b>{{d.name}}</b></td><td>{{departmentName(d.departmentId)}}</td><td>{{d.description||'—'}}</td><td><span class="pill">{{d.status||'ACTIVE'}}</span></td><td><button type="button" (click)="openEditDesignation(d)">Edit</button></td></tr><tr *ngIf="designations.length===0"><td colspan="6">No designations configured yet.</td></tr></tbody></table></div></div>
<div *ngIf="section==='attendance'"><div class="toolbar"><h2>Attendance</h2></div><table><thead><tr><th>Date</th><th>Employee ID</th><th>Status</th><th>Check in</th><th>Check out</th></tr></thead><tbody><tr *ngFor="let a of attendance"><td>{{a.attendanceDate}}</td><td>{{a.employeeId}}</td><td>{{a.status}}</td><td>{{a.checkIn||'—'}}</td><td>{{a.checkOut||'—'}}</td></tr></tbody></table></div>
<div *ngIf="section==='leaves'"><div class="toolbar"><h2>Leave management</h2></div><table><thead><tr><th>Employee</th><th>Type</th><th>Dates</th><th>Status</th><th>Action</th></tr></thead><tbody><tr *ngFor="let l of leaves"><td>{{employeeName(l.employeeId)}}</td><td>{{l.leaveType}}</td><td>{{l.startDate}} → {{l.endDate}}</td><td>{{l.status}}</td><td><button *ngIf="l.status==='PENDING'" (click)="approve(l)">Approve</button></td></tr></tbody></table></div>
<div *ngIf="section==='goals'"><div class="toolbar"><h2>Goals</h2></div><table><thead><tr><th>Employee</th><th>Goal</th><th>Progress</th><th>Due</th></tr></thead><tbody><tr *ngFor="let g of goals"><td>{{employeeName(g.employeeId)}}</td><td><b>{{g.title}}</b><br><small>{{g.description}}</small></td><td>{{g.currentValue||0}} / {{g.targetValue||0}}</td><td>{{g.dueDate||'—'}}</td></tr></tbody></table></div>
<div *ngIf="section==='reports'" class="feature-list"><div><strong>Workforce</strong><span>{{employees.length}} employees across {{departments.length}} departments; {{activeEmployees}} active.</span></div><div><strong>Leave</strong><span>{{pendingLeaves}} leave requests currently require approval.</span></div><div><strong>Attendance</strong><span>{{attendance.length}} attendance records loaded for the current reporting window.</span></div><div><strong>Goals</strong><span>{{goals.length}} objectives are currently tracked.</span></div></div>
<div *ngIf="['holidays','meetings','performance','knowledge','documents'].includes(section)" class="feature-list"><div><strong>{{sectionTitle}}</strong><span>The HR workspace is now wired to this section. Its dedicated domain model and lifecycle are the next HR expansion point; the shared role-aware shell and authorization boundary are already in place.</span></div></div>
<div *ngIf="newEmployee" class="modal"><form (ngSubmit)="saveEmployee()"><h2>New employee</h2><input required placeholder="Employee number" [(ngModel)]="draft.employeeNumber" name="number"><input required placeholder="First name" [(ngModel)]="draft.firstName" name="first"><input required placeholder="Last name" [(ngModel)]="draft.lastName" name="last"><input required type="email" placeholder="Email" [(ngModel)]="draft.email" name="email"><select [(ngModel)]="draft.departmentId" name="department"><option [ngValue]="undefined">No department</option><option *ngFor="let d of departments" [ngValue]="d.id">{{d.name}}</option></select><select [(ngModel)]="draft.designationId" name="designation"><option [ngValue]="undefined">No designation</option><option *ngFor="let d of designations" [ngValue]="d.id">{{d.name}}</option></select><div class="actions"><button type="button" (click)="newEmployee=false">Cancel</button><button type="submit">Create</button></div></form></div>
<div *ngIf="departmentModal" class="modal"><form (ngSubmit)="saveDepartment()"><h2>{{editingDepartment ? 'Edit department' : 'New department'}}</h2><p *ngIf="formError" role="alert">{{formError}}</p><input required maxlength="40" placeholder="Department code" [(ngModel)]="departmentDraft.code" name="code"><input required maxlength="160" placeholder="Department name" [(ngModel)]="departmentDraft.name" name="name"><select [(ngModel)]="departmentDraft.parentId" name="parent"><option [ngValue]="undefined">No parent</option><option *ngFor="let d of availableParents" [ngValue]="d.id">{{d.name}}</option></select><select [(ngModel)]="departmentDraft.status" name="status"><option value="ACTIVE">Active</option><option value="INACTIVE">Inactive</option></select><div class="actions"><button type="button" (click)="closeDepartmentModal()">Cancel</button><button type="submit">{{editingDepartment ? 'Save changes' : 'Create'}}</button></div></form></div><div *ngIf="designationModal" class="modal"><form (ngSubmit)="saveDesignation()"><h2>{{editingDesignation ? 'Edit designation' : 'New designation'}}</h2><p *ngIf="formError" role="alert">{{formError}}</p><input required maxlength="40" placeholder="Designation code" [(ngModel)]="designationDraft.code" name="designationCode"><input required maxlength="160" placeholder="Designation name" [(ngModel)]="designationDraft.name" name="designationName"><select [(ngModel)]="designationDraft.departmentId" name="designationDepartment"><option [ngValue]="undefined">All departments</option><option *ngFor="let d of departments" [ngValue]="d.id">{{d.name}}</option></select><textarea maxlength="500" placeholder="Description" [(ngModel)]="designationDraft.description" name="description"></textarea><select [(ngModel)]="designationDraft.status" name="designationStatus"><option value="ACTIVE">Active</option><option value="INACTIVE">Inactive</option></select><div class="actions"><button type="button" (click)="closeDesignationModal()">Cancel</button><button type="submit">{{editingDesignation ? 'Save changes' : 'Create'}}</button></div></form></div></section>`,styles:[`
:host .modal p[role="alert"]{margin:0 0 12px;padding:8px 10px;border-radius:4px;background:#f8d7da;color:#842029}
`]})
export class HrComponent implements OnInit {
 @Input() section='employees'; api=inject(HrApi); employees:Employee[]=[]; departments:Department[]=[]; designations:Designation[]=[]; attendance:Attendance[]=[]; leaves:LeaveRequest[]=[]; goals:Goal[]=[];
 newEmployee=false; departmentModal=false; editingDepartment=false; designationModal=false; editingDesignation=false; organizationView:'departments'|'designations'='departments'; formError=''; departmentDraft:Department={code:'',name:'',status:'ACTIVE'}; designationDraft:Designation={code:'',name:'',status:'ACTIVE'}; draft:Employee={employeeNumber:'',firstName:'',lastName:'',email:'',status:'ACTIVE'};
 async ngOnInit(){await this.reload();}
 async reload(){[this.employees,this.departments,this.designations,this.attendance,this.leaves,this.goals]=await Promise.all([this.api.employees(),this.api.departments(),this.api.designations(),this.api.attendance(),this.api.leaves(),this.api.goals()]);}
 get pendingLeaves(){return this.leaves.filter(x=>x.status==='PENDING').length;} get activeEmployees(){return this.employees.filter(x=>x.status==='ACTIVE').length;} get sectionTitle(){return this.section[0].toUpperCase()+this.section.slice(1);}
 get availableParents(){const currentId=this.departmentDraft.id;return this.departments.filter(d=>d.id!==currentId);}
 departmentName(id?:number){return id?this.departments.find(x=>x.id===id)?.name||`Department #${id}`:'—';}
 employeeName(id:number){const e=this.employees.find(x=>x.id===id);return e?`${e.firstName} ${e.lastName}`:`Employee #${id}`;}
 employeesInDepartment(id?:number){return this.employees.filter(x=>x.departmentId===id).length;}
 openNewEmployee(){this.draft={employeeNumber:'',firstName:'',lastName:'',email:'',status:'ACTIVE'};this.newEmployee=true;}
 openNewDepartment(){this.departmentDraft={code:'',name:'',status:'ACTIVE'};this.editingDepartment=false;this.formError='';this.departmentModal=true;}
 openEditDepartment(d:Department){this.departmentDraft={...d};this.editingDepartment=true;this.formError='';this.departmentModal=true;} openNewDesignation(){this.designationDraft={code:'',name:'',status:'ACTIVE'};this.editingDesignation=false;this.formError='';this.designationModal=true;} openEditDesignation(d:Designation){this.designationDraft={...d};this.editingDesignation=true;this.formError='';this.designationModal=true;} closeDesignationModal(){this.designationModal=false;this.editingDesignation=false;this.formError='';}
 closeDepartmentModal(){this.departmentModal=false;this.editingDepartment=false;this.formError='';}
 async saveEmployee(){if(this.draft.designationId)this.draft.designation=this.designations.find(x=>x.id===this.draft.designationId)?.name;await this.api.createEmployee(this.draft);this.newEmployee=false;await this.reload();}
 async saveDesignation(){this.formError='';try{if(this.editingDesignation){await this.api.updateDesignation(this.designationDraft);}else{await this.api.createDesignation(this.designationDraft);}this.closeDesignationModal();await this.reload();}catch(error:any){this.formError=error?.error?.error||error?.message||'Unable to save designation.';}} async saveDepartment(){this.formError='';try{if(this.editingDepartment){await this.api.updateDepartment(this.departmentDraft);}else{await this.api.createDepartment(this.departmentDraft);}this.closeDepartmentModal();await this.reload();}catch(error:any){this.formError=error?.error?.error||error?.message||'Unable to save department.';}}
 async approve(l:LeaveRequest){if(l.id){await this.api.updateLeave(l.id,'APPROVED');await this.reload();}}
}
