import {Component,inject,OnInit} from '@angular/core';
import {CommonModule} from '@angular/common'; import {FormsModule} from '@angular/forms'; import {InventoryApi,Material} from './inventory-api.service';
@Component({selector:'app-inventory',standalone:true,imports:[CommonModule,FormsModule],template:`
<div class="panel"><div class="toolbar"><div><h2>Inventory</h2><p>Manage materials, stock and customer dispatches.</p></div><button *ngIf="canManage" (click)="mode='material'">+ New material</button></div>
<div class="cards inventory-cards"><article><span>Materials</span><strong>{{materials.length}}</strong><small>Active material records</small></article><article><span>Units in stock</span><strong>{{totalStock}}</strong><small>Across main warehouse</small></article><article><span>Low stock</span><strong>{{lowStock}}</strong><small>At or below reorder level</small></article><article><span>Dispatches</span><strong>{{dispatches.length}}</strong><small>Recorded dispatches</small></article></div>
<div class="toolbar sub"><div><h3>Material inventory</h3></div><button *ngIf="canManage" (click)="mode='stock'">+ Stock In</button></div>
<table><thead><tr><th>SKU</th><th>Material</th><th>Unit</th><th>Available</th><th>Reorder</th><th>Status</th><th *ngIf="canManage">Actions</th></tr></thead><tbody><tr *ngFor="let m of materials"><td>{{m.sku}}</td><td><b>{{m.name}}</b><div class="muted">{{m.description || '—'}}</div></td><td>{{m.unit}}</td><td><b>{{m.quantity || 0}}</b></td><td>{{m.reorderLevel || 0}}</td><td><span class="pill">{{m.status}}</span></td><td *ngIf="canManage"><button (click)="selected=m;mode='adjust'">Adjust</button></td></tr></tbody></table><div class="empty" *ngIf="!materials.length">No materials yet.</div>
<div class="toolbar sub"><div><h3>Dispatch history</h3></div><button (click)="mode='dispatch'">+ Dispatch</button></div>
<table *ngIf="dispatches.length"><thead><tr><th>Dispatch</th><th>Customer</th><th>Reference</th><th>Date</th><th>Status</th><th>Items</th></tr></thead><tbody><tr *ngFor="let d of dispatches"><td><b>{{d.dispatchNumber}}</b></td><td>{{d.customerId}}</td><td>{{d.referenceNumber}}</td><td>{{d.dispatchDate | date:'medium'}}</td><td><span class="pill">{{d.status}}</span></td><td>{{d.items.length}}</td></tr></tbody></table>
</div>
<section *ngIf="mode" class="modal"><form (ngSubmit)="submit()"><h2>{{mode==='material'?'New material':mode==='stock'?'Stock in':mode==='adjust'?'Stock adjustment':'Dispatch materials'}}</h2>
<ng-container *ngIf="mode==='material'"><input required placeholder="Material code / SKU" [(ngModel)]="draft.sku" name="sku"><input required placeholder="Material name" [(ngModel)]="draft.name" name="name"><input placeholder="Description" [(ngModel)]="draft.description" name="description"><input required placeholder="Unit (PCS, EA, KG...)" [(ngModel)]="draft.unit" name="unit"><input type="number" min="0" placeholder="Initial quantity" [(ngModel)]="draft.initialQuantity" name="initialQuantity"><input type="number" min="0" placeholder="Minimum stock level" [(ngModel)]="draft.reorderLevel" name="reorderLevel"></ng-container>
<ng-container *ngIf="mode==='stock'||mode==='adjust'"><select required [(ngModel)]="selectedId" name="selectedId"><option [ngValue]="0">Select material</option><option *ngFor="let m of materials" [ngValue]="m.id">{{m.sku}} — {{m.name}} ({{m.quantity||0}})</option></select><input type="number" [min]="mode==='stock'?1:-999999" placeholder="Quantity" [(ngModel)]="quantity" name="quantity"><input required placeholder="Reference / reason" [(ngModel)]="reference" name="reference"><small *ngIf="mode==='adjust'">Use a positive number to add stock or a negative number to remove stock.</small></ng-container>
<ng-container *ngIf="mode==='dispatch'"><input type="number" required min="1" placeholder="Customer ID" [(ngModel)]="customerId" name="customerId"><select required [(ngModel)]="selectedId" name="dispatchMaterial"><option [ngValue]="0">Select material</option><option *ngFor="let m of materials" [ngValue]="m.id">{{m.sku}} — {{m.name}} ({{m.quantity||0}})</option></select><input type="number" required min="1" placeholder="Quantity" [(ngModel)]="quantity" name="dispatchQuantity"><input required placeholder="Sales order / reference" [(ngModel)]="reference" name="dispatchReference"><input placeholder="Delivery address" [(ngModel)]="address" name="address"><textarea placeholder="Notes" [(ngModel)]="notes" name="notes"></textarea></ng-container>
<div class="actions"><button type="button" (click)="mode=''">Cancel</button><button type="submit">Save</button></div></form></section>`,styles:[`.sub{margin-top:28px}.inventory-cards{margin-bottom:10px}.muted{font-size:12px;color:#667085}textarea{width:100%;min-height:80px;border:1px solid #d0d5dd;border-radius:8px;padding:11px;font:inherit}`]})
export class InventoryComponent implements OnInit {api=inject(InventoryApi);materials:Material[]=[];dispatches:any[]=[];mode='';selectedId=0;selected?:Material;quantity=0;reference='';customerId=0;address='';notes='';draft:Material={sku:'',name:'',unit:'PCS',initialQuantity:0,reorderLevel:0};canManage=true;
async ngOnInit(){await this.reload();}get totalStock(){return this.materials.reduce((a,m)=>a+(m.quantity||0),0);}get lowStock(){return this.materials.filter(m=>(m.quantity||0)<=(m.reorderLevel||0)).length;}async reload(){this.materials=await this.api.materials();this.dispatches=await this.api.history();}async submit(){try{if(this.mode==='material')await this.api.createMaterial(this.draft);if(this.mode==='stock')await this.api.stockIn(this.selectedId,this.quantity,this.reference);if(this.mode==='adjust')await this.api.adjustment(this.selectedId,this.quantity,this.reference);if(this.mode==='dispatch')await this.api.dispatch({customerId:this.customerId,referenceNumber:this.reference,deliveryAddress:this.address,notes:this.notes,items:[{productId:this.selectedId,warehouseId:1,quantity:this.quantity}]});this.mode='';this.draft={sku:'',name:'',unit:'PCS',initialQuantity:0,reorderLevel:0};this.quantity=0;this.reference='';await this.reload();}catch(e){alert(e)}}}
