import {Component,OnInit,inject} from '@angular/core';
import {CommonModule} from '@angular/common'; import {FormsModule} from '@angular/forms'; import {HttpClient,HttpHeaders} from '@angular/common/http'; import {firstValueFrom} from 'rxjs'; import {AuthService} from './auth.service';

@Component({selector:'app-procurement',standalone:true,imports:[CommonModule,FormsModule],template:`
<div class="panel"><div class="toolbar"><div><h2>Procurement</h2><p>Manage suppliers, purchase requests, purchase orders and goods received.</p></div><button (click)="mode='supplier'">+ Supplier</button></div>
<div class="cards"><article><span>Suppliers</span><strong>{{suppliers.length}}</strong><small>Active suppliers</small></article><article><span>Requests</span><strong>{{requests.length}}</strong><small>Purchase requests</small></article><article><span>Orders</span><strong>{{orders.length}}</strong><small>Purchase orders</small></article><article><span>Received</span><strong>{{receipts.length}}</strong><small>Goods receipts</small></article></div>
<div class="toolbar sub"><h3>Suppliers</h3><button (click)="mode='supplier'">+ Add supplier</button></div><table><thead><tr><th>Code</th><th>Supplier</th><th>Email</th><th>Phone</th><th>Status</th></tr></thead><tbody><tr *ngFor="let s of suppliers"><td>{{s.code}}</td><td><b>{{s.name}}</b></td><td>{{s.email||'—'}}</td><td>{{s.phone||'—'}}</td><td><span class="pill">{{s.status}}</span></td></tr></tbody></table>
<div class="toolbar sub"><h3>Purchase requests</h3><button (click)="mode='request'">+ Request</button></div><table><thead><tr><th>Request</th><th>Description</th><th>Estimated</th><th>Status</th><th>Requested by</th><th>Action</th></tr></thead><tbody><tr *ngFor="let r of requests"><td><b>{{r.requestNumber}}</b></td><td>{{r.description}}</td><td>₹{{r.estimatedAmount|number:'1.0-2'}}</td><td><span class="pill">{{r.status}}</span></td><td>{{r.requestedBy}}</td><td><select [ngModel]="r.status" (ngModelChange)="updateRequest(r.id,$event)"><option>PENDING</option><option>APPROVED</option><option>REJECTED</option><option>ORDERED</option><option>CANCELLED</option></select></td></tr></tbody></table>
<div class="toolbar sub"><h3>Purchase orders</h3><button (click)="mode='order'">+ Purchase order</button></div><table><thead><tr><th>Order</th><th>Supplier</th><th>Lines</th><th>Amount</th><th>Status</th><th>Date</th><th>Action</th></tr></thead><tbody><tr *ngFor="let o of orders"><td><b>{{o.orderNumber}}</b></td><td>{{supplierName(o.supplierId)}}</td><td>{{o.items?.length||0}}</td><td>₹{{o.amount|number:'1.0-2'}}</td><td><span class="pill">{{o.status}}</span></td><td>{{o.orderDate|date:'mediumDate'}}</td><td><select [ngModel]="o.status" (ngModelChange)="updateOrder(o.id,$event)"><option>ISSUED</option><option>PARTIALLY_RECEIVED</option><option>RECEIVED</option><option>CANCELLED</option></select></td></tr></tbody></table>
<div class="toolbar sub"><h3>Goods received</h3><button (click)="mode='receipt'">+ Receive goods</button></div><table><thead><tr><th>Receipt</th><th>PO</th><th>Material</th><th>Warehouse</th><th>Quantity</th><th>Status</th><th>Date</th></tr></thead><tbody><tr *ngFor="let r of receipts"><td><b>{{r.receiptNumber}}</b></td><td>{{orderName(r.purchaseOrderId)}}</td><td>{{materialName(r.productId)}}</td><td>{{warehouseName(r.warehouseId)}}</td><td>{{r.quantity}}</td><td><span class="pill">{{r.status}}</span></td><td>{{r.receivedAt|date:'medium'}}</td></tr></tbody></table></div>
<section *ngIf="mode" class="modal"><form (ngSubmit)="submit()"><h2>{{mode==='supplier'?'New supplier':mode==='request'?'Purchase request':mode==='order'?'Purchase order':'Receive goods'}}</h2>
<ng-container *ngIf="mode==='supplier'"><input required placeholder="Supplier code" [(ngModel)]="supplier.code" name="code"><input required placeholder="Supplier name" [(ngModel)]="supplier.name" name="name"><input type="email" placeholder="Email" [(ngModel)]="supplier.email" name="email"><input placeholder="Phone" [(ngModel)]="supplier.phone" name="phone"><input placeholder="Address" [(ngModel)]="supplier.address" name="address"></ng-container>
<ng-container *ngIf="mode==='request'"><textarea required placeholder="What needs to be purchased?" [(ngModel)]="request.description" name="description"></textarea><input type="number" min="0" placeholder="Estimated amount" [(ngModel)]="request.estimatedAmount" name="estimatedAmount"></ng-container>
<ng-container *ngIf="mode==='order'"><select required [(ngModel)]="order.supplierId" name="supplierId"><option [ngValue]="0">Select supplier</option><option *ngFor="let s of suppliers" [ngValue]="s.id">{{s.code}} — {{s.name}}</option></select><div class="line" *ngFor="let item of order.items; let i=index"><select required [(ngModel)]="item.productId" [name]="'product'+i"><option [ngValue]="0">Material</option><option *ngFor="let m of materials" [ngValue]="m.id">{{m.sku}} — {{m.name}}</option></select><select required [(ngModel)]="item.warehouseId" [name]="'warehouse'+i"><option [ngValue]="0">Warehouse</option><option *ngFor="let w of warehouses" [ngValue]="w.id">{{w.code}} — {{w.name}}</option></select><input type="number" min="0.01" required placeholder="Qty" [(ngModel)]="item.quantity" [name]="'qty'+i"><input type="number" min="0" required placeholder="Unit price" [(ngModel)]="item.unitPrice" [name]="'price'+i"><button type="button" (click)="removeOrderItem(i)">×</button></div><button type="button" (click)="addOrderItem()">+ Add line</button></ng-container>
<ng-container *ngIf="mode==='receipt'"><select required [(ngModel)]="receipt.purchaseOrderId" name="purchaseOrderId" (ngModelChange)="syncReceiptLine()"><option [ngValue]="0">Select purchase order</option><option *ngFor="let o of receivableOrders" [ngValue]="o.id">{{o.orderNumber}} — ₹{{o.amount}}</option></select><select required [(ngModel)]="receipt.productId" name="productId" (ngModelChange)="syncReceiptWarehouse()"><option [ngValue]="0">Select material</option><option *ngFor="let i of selectedOrder?.items||[]" [ngValue]="i.productId">{{materialName(i.productId)}}</option></select><select required [(ngModel)]="receipt.warehouseId" name="warehouseId"><option [ngValue]="0">Select warehouse</option><option *ngFor="let i of selectedOrder?.items||[]" [ngValue]="i.warehouseId">{{warehouseName(i.warehouseId)}}</option></select><input type="number" min="0.01" required placeholder="Received quantity" [(ngModel)]="receipt.quantity" name="quantity"></ng-container>
<div class="actions"><button type="button" (click)="mode=''">Cancel</button><button type="submit">Save</button></div></form></section>`,styles:[`.sub{margin-top:28px}.line{display:grid;grid-template-columns:1.4fr 1.2fr .7fr .9fr auto;gap:8px;align-items:center;margin:8px 0}textarea{width:100%;min-height:80px;padding:11px}select{max-width:260px}`]})
export class ProcurementComponent implements OnInit {
 http=inject(HttpClient);auth=inject(AuthService);base='/api/v1/procurement';inventoryBase='/api/v1/inventory';suppliers:any[]=[];requests:any[]=[];orders:any[]=[];receipts:any[]=[];materials:any[]=[];warehouses:any[]=[];mode='';
 supplier:any={code:'',name:'',email:'',phone:'',address:''};request:any={description:'',estimatedAmount:0,requestedBy:'user'};order:any={supplierId:0,items:[this.newOrderItem()]};receipt:any={purchaseOrderId:0,productId:0,warehouseId:0,quantity:0};
 async ngOnInit(){await this.reload()}
 async headers(){return{headers:new HttpHeaders({'Authorization':`Bearer ${await this.auth.token()}`,'X-Tenant-ID':'1'})}}
 async reload(){const h=await this.headers();[this.suppliers,this.requests,this.orders,this.receipts,this.warehouses]=await Promise.all([firstValueFrom(this.http.get<any[]>(this.base+'/suppliers',h)),firstValueFrom(this.http.get<any[]>(this.base+'/requests',h)),firstValueFrom(this.http.get<any[]>(this.base+'/orders',h)),firstValueFrom(this.http.get<any[]>(this.base+'/goods-received',h)),firstValueFrom(this.http.get<any[]>(this.inventoryBase+'/warehouses',h))]);if(this.warehouses.length)this.materials=await firstValueFrom(this.http.get<any[]>(this.inventoryBase+'/materials',{...h,params:{warehouseId:this.warehouses[0].id}}));}
 get receivableOrders(){return this.orders.filter(x=>x.status==='ISSUED'||x.status==='PARTIALLY_RECEIVED');} get selectedOrder(){return this.orders.find(x=>x.id===this.receipt.purchaseOrderId);}
 newOrderItem(){return{productId:0,warehouseId:0,quantity:1,unitPrice:0}} addOrderItem(){this.order.items.push(this.newOrderItem())} removeOrderItem(i:number){if(this.order.items.length>1)this.order.items.splice(i,1)}
 supplierName(id:number){return this.suppliers.find(x=>x.id===id)?.name||`Supplier #${id}`;} orderName(id:number){return this.orders.find(x=>x.id===id)?.orderNumber||`PO #${id}`;} materialName(id:number){return this.materials.find(x=>x.id===id)?.name||`Material #${id}`;} warehouseName(id:number){return this.warehouses.find(x=>x.id===id)?.name||`Warehouse #${id}`;}
 syncReceiptLine(){this.receipt.productId=0;this.receipt.warehouseId=0;this.receipt.quantity=0} syncReceiptWarehouse(){const line=this.selectedOrder?.items?.find((i:any)=>i.productId===this.receipt.productId);if(line)this.receipt.warehouseId=line.warehouseId}
 async updateRequest(id:number,status:string){try{const h=await this.headers();await firstValueFrom(this.http.patch(this.base+`/requests/${id}`,{}, {...h,params:{status}}));await this.reload();}catch(e:any){alert(e?.error?.message||'Unable to update request')}}
 async updateOrder(id:number,status:string){try{const h=await this.headers();await firstValueFrom(this.http.patch(this.base+`/orders/${id}`,{}, {...h,params:{status}}));await this.reload();}catch(e:any){alert(e?.error?.message||'Unable to update order')}}
 async submit(){try{const h=await this.headers();let path='';let body:any;if(this.mode==='supplier'){path='suppliers';body=this.supplier;}if(this.mode==='request'){path='requests';body=this.request;}if(this.mode==='order'){path='orders';body=this.order;}if(this.mode==='receipt'){path='goods-received';body=this.receipt;}await firstValueFrom(this.http.post(this.base+'/'+path,body,h));this.mode='';await this.reload();}catch(e:any){alert(e?.error?.message||'Request failed')}}
}
