import {Component,OnInit,inject} from '@angular/core';
import {CommonModule} from '@angular/common'; import {FormsModule} from '@angular/forms'; import {HttpClient,provideHttpClient} from '@angular/common/http';

@Component({selector:'app-procurement',standalone:true,imports:[CommonModule,FormsModule],template:`
<div class="panel"><div class="toolbar"><div><h2>Procurement</h2><p>Manage suppliers, purchase requests, purchase orders and goods received.</p></div><button (click)="mode='supplier'">+ Supplier</button></div>
<div class="cards"><article><span>Suppliers</span><strong>{{suppliers.length}}</strong><small>Active suppliers</small></article><article><span>Requests</span><strong>{{requests.length}}</strong><small>Purchase requests</small></article><article><span>Orders</span><strong>{{orders.length}}</strong><small>Purchase orders</small></article><article><span>Received</span><strong>{{receipts.length}}</strong><small>Goods receipts</small></article></div>
<div class="toolbar sub"><h3>Suppliers</h3><button (click)="mode='supplier'">+ Add supplier</button></div><table><thead><tr><th>Code</th><th>Supplier</th><th>Email</th><th>Phone</th><th>Status</th></tr></thead><tbody><tr *ngFor="let s of suppliers"><td>{{s.code}}</td><td><b>{{s.name}}</b></td><td>{{s.email||'—'}}</td><td>{{s.phone||'—'}}</td><td><span class="pill">{{s.status}}</span></td></tr></tbody></table>
<div class="toolbar sub"><h3>Purchase requests</h3><button (click)="mode='request'">+ Request</button></div><table><thead><tr><th>Request</th><th>Description</th><th>Estimated</th><th>Status</th><th>Requested by</th></tr></thead><tbody><tr *ngFor="let r of requests"><td><b>{{r.requestNumber}}</b></td><td>{{r.description}}</td><td>₹{{r.estimatedAmount|number:'1.0-2'}}</td><td><span class="pill">{{r.status}}</span></td><td>{{r.requestedBy}}</td></tr></tbody></table>
<div class="toolbar sub"><h3>Purchase orders</h3><button (click)="mode='order'">+ Purchase order</button></div><table><thead><tr><th>Order</th><th>Supplier ID</th><th>Amount</th><th>Status</th><th>Date</th></tr></thead><tbody><tr *ngFor="let o of orders"><td><b>{{o.orderNumber}}</b></td><td>{{o.supplierId}}</td><td>₹{{o.amount|number:'1.0-2'}}</td><td><span class="pill">{{o.status}}</span></td><td>{{o.orderDate|date:'mediumDate'}}</td></tr></tbody></table>
<div class="toolbar sub"><h3>Goods received</h3><button (click)="mode='receipt'">+ Receive goods</button></div><table><thead><tr><th>Receipt</th><th>PO ID</th><th>Quantity</th><th>Status</th><th>Date</th></tr></thead><tbody><tr *ngFor="let r of receipts"><td><b>{{r.receiptNumber}}</b></td><td>{{r.purchaseOrderId}}</td><td>{{r.quantity}}</td><td><span class="pill">{{r.status}}</span></td><td>{{r.receivedAt|date:'medium'}}</td></tr></tbody></table></div>
<section *ngIf="mode" class="modal"><form (ngSubmit)="submit()"><h2>{{mode==='supplier'?'New supplier':mode==='request'?'Purchase request':mode==='order'?'Purchase order':'Receive goods'}}</h2>
<ng-container *ngIf="mode==='supplier'"><input required placeholder="Supplier code" [(ngModel)]="supplier.code" name="code"><input required placeholder="Supplier name" [(ngModel)]="supplier.name" name="name"><input type="email" placeholder="Email" [(ngModel)]="supplier.email" name="email"><input placeholder="Phone" [(ngModel)]="supplier.phone" name="phone"><input placeholder="Address" [(ngModel)]="supplier.address" name="address"></ng-container>
<ng-container *ngIf="mode==='request'"><textarea required placeholder="What needs to be purchased?" [(ngModel)]="request.description" name="description"></textarea><input type="number" min="0" placeholder="Estimated amount" [(ngModel)]="request.estimatedAmount" name="estimatedAmount"></ng-container>
<ng-container *ngIf="mode==='order'"><select required [(ngModel)]="order.supplierId" name="supplierId"><option [ngValue]="0">Select supplier</option><option *ngFor="let s of suppliers" [ngValue]="s.id">{{s.code}} — {{s.name}}</option></select><input type="number" min="0" required placeholder="Order amount" [(ngModel)]="order.amount" name="amount"></ng-container>
<ng-container *ngIf="mode==='receipt'"><input type="number" min="1" required placeholder="Purchase order ID" [(ngModel)]="receipt.purchaseOrderId" name="purchaseOrderId"><input type="number" min="0.01" required placeholder="Received quantity" [(ngModel)]="receipt.quantity" name="quantity"></ng-container>
<div class="actions"><button type="button" (click)="mode=''">Cancel</button><button type="submit">Save</button></div></form></section>`,styles:[`.sub{margin-top:28px}textarea{width:100%;min-height:80px;padding:11px}`]})
export class ProcurementComponent implements OnInit {http=inject(HttpClient);base='/api/v1/procurement';suppliers:any[]=[];requests:any[]=[];orders:any[]=[];receipts:any[]=[];mode='';supplier:any={code:'',name:'',email:'',phone:'',address:''};request:any={description:'',estimatedAmount:0,requestedBy:'user'};order:any={supplierId:0,amount:0};receipt:any={purchaseOrderId:0,quantity:0};
 ngOnInit(){this.reload()} headers(){return {headers:{Authorization:`Bearer ${localStorage.getItem('sivion_token')||''}`,'X-Tenant-ID':'1'}}} reload(){this.http.get<any[]>(this.base+'/suppliers',this.headers()).subscribe(x=>this.suppliers=x);this.http.get<any[]>(this.base+'/requests',this.headers()).subscribe(x=>this.requests=x);this.http.get<any[]>(this.base+'/orders',this.headers()).subscribe(x=>this.orders=x);this.http.get<any[]>(this.base+'/goods-received',this.headers()).subscribe(x=>this.receipts=x)} submit(){let req:any;if(this.mode==='supplier')req=this.http.post(this.base+'/suppliers',this.supplier,this.headers());if(this.mode==='request')req=this.http.post(this.base+'/requests',this.request,this.headers());if(this.mode==='order')req=this.http.post(this.base+'/orders',this.order,this.headers());if(this.mode==='receipt')req=this.http.post(this.base+'/goods-received',this.receipt,this.headers());req.subscribe({next:()=>{this.mode='';this.reload()},error:e=>alert(e?.error?.message||'Request failed')})}}
