package com.sivion.api.procurement.service;

import com.sivion.api.integration.DomainEventPublisher;
import com.sivion.api.procurement.domain.*; import com.sivion.api.procurement.repo.*;
import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import java.math.BigDecimal; import java.time.Instant; import java.util.*;

@Service public class ProcurementService {
 private static final long TENANT=1L; private final SupplierRepository suppliers; private final PurchaseRequestRepository requests; private final PurchaseOrderRepository orders; private final PurchaseOrderItemRepository orderItems; private final GoodsReceiptRepository receipts; private final DomainEventPublisher events;
 public ProcurementService(SupplierRepository s,PurchaseRequestRepository r,PurchaseOrderRepository o,PurchaseOrderItemRepository oi,GoodsReceiptRepository g,DomainEventPublisher events){suppliers=s;requests=r;orders=o;orderItems=oi;receipts=g;this.events=events;}
 public List<SupplierView> suppliers(){return suppliers.findByTenantIdOrderByName(TENANT).stream().map(s->new SupplierView(s.getId(),s.getCode(),s.getName(),s.getEmail(),s.getPhone(),s.getAddress(),s.getStatus())).toList();}
 @Transactional public SupplierView createSupplier(SupplierRequest r){if(r.code()==null||r.code().isBlank()||r.name()==null||r.name().isBlank())throw new IllegalArgumentException("Supplier code and name are required");String code=r.code().trim().toUpperCase(Locale.ROOT);if(suppliers.existsByTenantIdAndCode(TENANT,code))throw new IllegalArgumentException("Supplier code already exists");Supplier s=new Supplier();s.setTenantId(TENANT);s.setCode(code);s.setName(r.name().trim());s.setEmail(r.email());s.setPhone(r.phone());s.setAddress(r.address());s.setStatus("ACTIVE");return map(suppliers.save(s));}
 public List<RequestView> requests(){return requests.findByTenantIdOrderByRequestedAtDesc(TENANT).stream().map(r->new RequestView(r.getId(),r.getRequestNumber(),r.getDescription(),r.getEstimatedAmount(),r.getStatus(),r.getRequestedBy(),r.getRequestedAt())).toList();}
 @Transactional public RequestView createRequest(RequestRequest x){if(x.description()==null||x.description().isBlank())throw new IllegalArgumentException("Description is required");if(x.estimatedAmount()!=null&&x.estimatedAmount().signum()<0)throw new IllegalArgumentException("Estimated amount cannot be negative");PurchaseRequest r=new PurchaseRequest();r.setTenantId(TENANT);r.setRequestNumber("PR-"+UUID.randomUUID().toString().substring(0,8).toUpperCase());r.setDescription(x.description().trim());r.setEstimatedAmount(x.estimatedAmount()==null?BigDecimal.ZERO:x.estimatedAmount());r.setRequestedBy(x.requestedBy()==null||x.requestedBy().isBlank()?"system":x.requestedBy().trim());r.setStatus("PENDING");return map(requests.save(r));}
 @Transactional public RequestView updateRequestStatus(Long id,String status){PurchaseRequest r=requests.findById(id).filter(x->x.getTenantId().equals(TENANT)).orElseThrow(()->new NoSuchElementException("Purchase request not found"));String next=normalizeStatus(status);validateTransition(r.getStatus(),next,"PENDING","APPROVED","REJECTED","ORDERED","CANCELLED");r.setStatus(next);return map(requests.save(r));}
 public List<OrderView> orders(){return orders.findByTenantIdOrderByOrderDateDesc(TENANT).stream().map(o->new OrderView(o.getId(),o.getOrderNumber(),o.getSupplierId(),o.getAmount(),o.getStatus(),o.getOrderDate(),orderItems.findByPurchaseOrderId(o.getId()).stream().map(i->new OrderItemView(i.getProductId(),i.getWarehouseId(),i.getQuantity(),i.getUnitPrice())).toList())).toList();}
 @Transactional public OrderView createOrder(OrderRequest x){if(x.supplierId()==null||suppliers.findByIdAndTenantId(x.supplierId(),TENANT).isEmpty())throw new NoSuchElementException("Supplier not found");if(x.items()==null||x.items().isEmpty())throw new IllegalArgumentException("At least one purchase order item is required");BigDecimal total=BigDecimal.ZERO;Set<String> uniqueLines=new HashSet<>();PurchaseOrder o=new PurchaseOrder();o.setTenantId(TENANT);o.setOrderNumber("PO-"+UUID.randomUUID().toString().substring(0,8).toUpperCase());o.setSupplierId(x.supplierId());o.setStatus("ISSUED");o=orders.save(o);List<PurchaseOrderItem> lines=new ArrayList<>();for(OrderItemRequest i:x.items()){if(i.productId()==null||i.warehouseId()==null||i.quantity()==null||i.quantity().signum()<=0||i.unitPrice()==null||i.unitPrice().signum()<0)throw new IllegalArgumentException("Each purchase order item requires product, warehouse, positive quantity and non-negative unit price");String lineKey=i.productId()+":"+i.warehouseId();if(!uniqueLines.add(lineKey))throw new IllegalArgumentException("Duplicate material and warehouse line in purchase order");PurchaseOrderItem item=new PurchaseOrderItem();item.setPurchaseOrderId(o.getId());item.setProductId(i.productId());item.setWarehouseId(i.warehouseId());item.setQuantity(i.quantity());item.setUnitPrice(i.unitPrice());lines.add(item);total=total.add(i.quantity().multiply(i.unitPrice()));}o.setAmount(total);orders.save(o);orderItems.saveAll(lines);return map(o);}
 @Transactional public OrderView updateOrderStatus(Long id,String status){PurchaseOrder o=orders.findById(id).filter(x->x.getTenantId().equals(TENANT)).orElseThrow(()->new NoSuchElementException("Purchase order not found"));String next=normalizeStatus(status);validateTransition(o.getStatus(),next,"ISSUED","PARTIALLY_RECEIVED","RECEIVED","CANCELLED");o.setStatus(next);return map(o);}
 public List<ReceiptView> receipts(){return receipts.findByTenantIdOrderByReceivedAtDesc(TENANT).stream().map(this::map).toList();}
 @Transactional public ReceiptView receive(ReceiptRequest x){PurchaseOrder o=orders.findById(x.purchaseOrderId()).filter(p->p.getTenantId().equals(TENANT)).orElseThrow(()->new NoSuchElementException("Purchase order not found"));if("CANCELLED".equals(o.getStatus())||"RECEIVED".equals(o.getStatus()))throw new IllegalStateException("Purchase order cannot receive additional goods in status "+o.getStatus());if(x.productId()==null||x.warehouseId()==null)throw new IllegalArgumentException("Product and warehouse are required");if(x.quantity()==null||x.quantity().signum()<=0)throw new IllegalArgumentException("Received quantity must be greater than zero");PurchaseOrderItem line=orderItems.findByPurchaseOrderId(o.getId()).stream().filter(i->i.getProductId().equals(x.productId())&&i.getWarehouseId().equals(x.warehouseId())).findFirst().orElseThrow(()->new IllegalArgumentException("Product and warehouse are not part of the purchase order"));BigDecimal alreadyReceived=receipts.receivedQuantity(TENANT,o.getId(),x.productId(),x.warehouseId());if(alreadyReceived.add(x.quantity()).compareTo(line.getQuantity())>0)throw new IllegalArgumentException("Received quantity exceeds remaining ordered quantity");GoodsReceipt r=new GoodsReceipt();r.setTenantId(TENANT);r.setReceiptNumber("GR-"+UUID.randomUUID().toString().substring(0,8).toUpperCase());r.setPurchaseOrderId(x.purchaseOrderId());r.setProductId(x.productId());r.setWarehouseId(x.warehouseId());r.setQuantity(x.quantity());r.setStatus("RECEIVED");r.setReceivedAt(Instant.now());orders.save(o);r=receipts.save(r);o.setStatus(isFullyReceived(o.getId())?"RECEIVED":"PARTIALLY_RECEIVED");orders.save(o);events.publish("procurement.goods-received",Map.of("goodsReceiptId",r.getId(),"purchaseOrderId",r.getPurchaseOrderId(),"productId",r.getProductId(),"warehouseId",r.getWarehouseId(),"quantity",r.getQuantity()));return map(r);}
 private boolean isFullyReceived(Long purchaseOrderId){for(PurchaseOrderItem item:orderItems.findByPurchaseOrderId(purchaseOrderId)){BigDecimal received=receipts.receivedQuantity(TENANT,purchaseOrderId,item.getProductId(),item.getWarehouseId());if(received.compareTo(item.getQuantity())<0)return false;}return true;}
 private String normalizeStatus(String status){if(status==null||status.isBlank())throw new IllegalArgumentException("Status is required");return status.trim().toUpperCase(Locale.ROOT);}
 private void validateTransition(String current,String next,String... allowed){if(Arrays.stream(allowed).noneMatch(next::equals))throw new IllegalArgumentException("Invalid status: "+next);if("CANCELLED".equals(current)||"RECEIVED".equals(current)||"REJECTED".equals(current))throw new IllegalStateException("Status cannot change from "+current);if("PENDING".equals(current)&&!(next.equals("APPROVED")||next.equals("REJECTED")||next.equals("CANCELLED")))throw new IllegalStateException("Invalid transition from PENDING to "+next);if("APPROVED".equals(current)&&!(next.equals("ORDERED")||next.equals("CANCELLED")))throw new IllegalStateException("Invalid transition from APPROVED to "+next);if("ISSUED".equals(current)&&!(next.equals("PARTIALLY_RECEIVED")||next.equals("RECEIVED")||next.equals("CANCELLED")))throw new IllegalStateException("Invalid transition from ISSUED to "+next);if("PARTIALLY_RECEIVED".equals(current)&&!(next.equals("RECEIVED")||next.equals("CANCELLED")))throw new IllegalStateException("Invalid transition from PARTIALLY_RECEIVED to "+next);}
 private SupplierView map(Supplier s){return new SupplierView(s.getId(),s.getCode(),s.getName(),s.getEmail(),s.getPhone(),s.getAddress(),s.getStatus());} private RequestView map(PurchaseRequest r){return new RequestView(r.getId(),r.getRequestNumber(),r.getDescription(),r.getEstimatedAmount(),r.getStatus(),r.getRequestedBy(),r.getRequestedAt());} private OrderView map(PurchaseOrder o){return new OrderView(o.getId(),o.getOrderNumber(),o.getSupplierId(),o.getAmount(),o.getStatus(),o.getOrderDate(),orderItems.findByPurchaseOrderId(o.getId()).stream().map(i->new OrderItemView(i.getProductId(),i.getWarehouseId(),i.getQuantity(),i.getUnitPrice())).toList());} private ReceiptView map(GoodsReceipt r){return new ReceiptView(r.getId(),r.getReceiptNumber(),r.getPurchaseOrderId(),r.getProductId(),r.getWarehouseId(),r.getQuantity(),r.getStatus(),r.getReceivedAt());}
 public record SupplierRequest(String code,String name,String email,String phone,String address){} public record SupplierView(Long id,String code,String name,String email,String phone,String address,String status){} public record RequestRequest(String description,BigDecimal estimatedAmount,String requestedBy){} public record RequestView(Long id,String requestNumber,String description,BigDecimal estimatedAmount,String status,String requestedBy,String requestedAt){} public record OrderItemRequest(Long productId,Long warehouseId,BigDecimal quantity,BigDecimal unitPrice){} public record OrderItemView(Long productId,Long warehouseId,BigDecimal quantity,BigDecimal unitPrice){} public record OrderRequest(Long supplierId,List<OrderItemRequest> items){} public record OrderView(Long id,String orderNumber,Long supplierId,BigDecimal amount,String status,Instant orderDate,List<OrderItemView> items){} public record ReceiptRequest(Long purchaseOrderId,Long productId,Long warehouseId,BigDecimal quantity){} public record ReceiptView(Long id,String receiptNumber,Long purchaseOrderId,Long productId,Long warehouseId,BigDecimal quantity,String status,Instant receivedAt){}
}
