package com.sivion.api.procurement.service;

import com.sivion.api.procurement.domain.*; import com.sivion.api.procurement.repo.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.math.BigDecimal; import java.time.Instant; import java.util.*;

@Service public class ProcurementService {
 private static final long TENANT=1L; private final SupplierRepository suppliers; private final PurchaseRequestRepository requests; private final PurchaseOrderRepository orders; private final GoodsReceiptRepository receipts;
 public ProcurementService(SupplierRepository s,PurchaseRequestRepository r,PurchaseOrderRepository o,GoodsReceiptRepository g){suppliers=s;requests=r;orders=o;receipts=g;}
 public List<SupplierView> suppliers(){return suppliers.findByTenantIdOrderByName(TENANT).stream().map(s->new SupplierView(s.getId(),s.getCode(),s.getName(),s.getEmail(),s.getPhone(),s.getAddress(),s.getStatus())).toList();}
 @Transactional public SupplierView createSupplier(SupplierRequest r){if(r.code()==null||r.code().isBlank()||r.name()==null||r.name().isBlank())throw new IllegalArgumentException("Supplier code and name are required");String code=r.code().trim();if(suppliers.existsByTenantIdAndCode(TENANT,code))throw new IllegalArgumentException("Supplier code already exists");Supplier s=new Supplier();s.setTenantId(TENANT);s.setCode(code);s.setName(r.name().trim());s.setEmail(r.email());s.setPhone(r.phone());s.setAddress(r.address());s.setStatus("ACTIVE");return map(suppliers.save(s));}
 public List<RequestView> requests(){return requests.findByTenantIdOrderByRequestedAtDesc(TENANT).stream().map(r->new RequestView(r.getId(),r.getRequestNumber(),r.getDescription(),r.getEstimatedAmount(),r.getStatus(),r.getRequestedBy(),r.getRequestedAt())).toList();}
 @Transactional public RequestView createRequest(RequestRequest x){if(x.description()==null||x.description().isBlank())throw new IllegalArgumentException("Description is required");if(x.estimatedAmount()!=null&&x.estimatedAmount().signum()<0)throw new IllegalArgumentException("Estimated amount cannot be negative");PurchaseRequest r=new PurchaseRequest();r.setTenantId(TENANT);r.setRequestNumber("PR-"+UUID.randomUUID().toString().substring(0,8).toUpperCase());r.setDescription(x.description().trim());r.setEstimatedAmount(x.estimatedAmount()==null?BigDecimal.ZERO:x.estimatedAmount());r.setRequestedBy(x.requestedBy()==null||x.requestedBy().isBlank()?"system":x.requestedBy().trim());r.setStatus("PENDING");return map(requests.save(r));}
 @Transactional public RequestView updateRequestStatus(Long id,String status){PurchaseRequest r=requests.findById(id).filter(x->x.getTenantId().equals(TENANT)).orElseThrow(()->new NoSuchElementException("Purchase request not found"));validateStatus(status,"PENDING","APPROVED","REJECTED","ORDERED","CANCELLED");r.setStatus(status);return map(requests.save(r));}
 public List<OrderView> orders(){return orders.findByTenantIdOrderByOrderDateDesc(TENANT).stream().map(o->new OrderView(o.getId(),o.getOrderNumber(),o.getSupplierId(),o.getAmount(),o.getStatus(),o.getOrderDate())).toList();}
 @Transactional public OrderView createOrder(OrderRequest x){if(x.supplierId()==null||suppliers.findByIdAndTenantId(x.supplierId(),TENANT).isEmpty())throw new NoSuchElementException("Supplier not found");if(x.amount()==null||x.amount().signum()<0)throw new IllegalArgumentException("Amount must be zero or greater");PurchaseOrder o=new PurchaseOrder();o.setTenantId(TENANT);o.setOrderNumber("PO-"+UUID.randomUUID().toString().substring(0,8).toUpperCase());o.setSupplierId(x.supplierId());o.setAmount(x.amount());o.setStatus("ISSUED");return map(orders.save(o));}
 @Transactional public OrderView updateOrderStatus(Long id,String status){PurchaseOrder o=orders.findById(id).filter(x->x.getTenantId().equals(TENANT)).orElseThrow(()->new NoSuchElementException("Purchase order not found"));validateStatus(status,"ISSUED","PARTIALLY_RECEIVED","RECEIVED","CANCELLED");o.setStatus(status);return map(orders.save(o));}
 public List<ReceiptView> receipts(){return receipts.findByTenantIdOrderByReceivedAtDesc(TENANT).stream().map(r->new ReceiptView(r.getId(),r.getReceiptNumber(),r.getPurchaseOrderId(),r.getQuantity(),r.getStatus(),r.getReceivedAt())).toList();}
 @Transactional public ReceiptView receive(ReceiptRequest x){PurchaseOrder o=orders.findById(x.purchaseOrderId()).filter(p->p.getTenantId().equals(TENANT)).orElseThrow(()->new NoSuchElementException("Purchase order not found"));if(x.quantity()==null||x.quantity().signum()<=0)throw new IllegalArgumentException("Received quantity must be greater than zero");GoodsReceipt r=new GoodsReceipt();r.setTenantId(TENANT);r.setReceiptNumber("GR-"+UUID.randomUUID().toString().substring(0,8).toUpperCase());r.setPurchaseOrderId(x.purchaseOrderId());r.setQuantity(x.quantity());r.setStatus("RECEIVED");r.setReceivedAt(Instant.now());o.setStatus("RECEIVED");orders.save(o);return map(receipts.save(r));}
 private void validateStatus(String status,String... allowed){if(status==null||Arrays.stream(allowed).noneMatch(status::equals))throw new IllegalArgumentException("Invalid status: "+status);}
 private SupplierView map(Supplier s){return new SupplierView(s.getId(),s.getCode(),s.getName(),s.getEmail(),s.getPhone(),s.getAddress(),s.getStatus());} private RequestView map(PurchaseRequest r){return new RequestView(r.getId(),r.getRequestNumber(),r.getDescription(),r.getEstimatedAmount(),r.getStatus(),r.getRequestedBy(),r.getRequestedAt());} private OrderView map(PurchaseOrder o){return new OrderView(o.getId(),o.getOrderNumber(),o.getSupplierId(),o.getAmount(),o.getStatus(),o.getOrderDate());} private ReceiptView map(GoodsReceipt r){return new ReceiptView(r.getId(),r.getReceiptNumber(),r.getPurchaseOrderId(),r.getQuantity(),r.getStatus(),r.getReceivedAt());}
 public record SupplierRequest(String code,String name,String email,String phone,String address){} public record SupplierView(Long id,String code,String name,String email,String phone,String address,String status){} public record RequestRequest(String description,BigDecimal estimatedAmount,String requestedBy){} public record RequestView(Long id,String requestNumber,String description,BigDecimal estimatedAmount,String status,String requestedBy,Instant requestedAt){} public record OrderRequest(Long supplierId,BigDecimal amount){} public record OrderView(Long id,String orderNumber,Long supplierId,BigDecimal amount,String status,Instant orderDate){} public record ReceiptRequest(Long purchaseOrderId,BigDecimal quantity){} public record ReceiptView(Long id,String receiptNumber,Long purchaseOrderId,BigDecimal quantity,String status,Instant receivedAt){}
}
