package com.sivion.api.inventory.service;

import com.sivion.api.inventory.domain.*; import com.sivion.api.inventory.repo.*; import jakarta.transaction.Transactional; import org.springframework.stereotype.Service; import java.math.BigDecimal; import java.time.Instant; import java.util.*;
@Service public class InventoryService {
 private static final long TENANT=1L; private final MaterialRepository materials; private final WarehouseRepository warehouses; private final InventoryTransactionRepository transactions; private final DispatchRepository dispatches;
 public InventoryService(MaterialRepository m,WarehouseRepository w,InventoryTransactionRepository t,DispatchRepository d){materials=m;warehouses=w;transactions=t;dispatches=d;}
 public List<WarehouseView> warehouses(){return warehouses.findByTenantIdOrderByName(TENANT).stream().map(w->new WarehouseView(w.getId(),w.getCode(),w.getName(),w.getStatus())).toList();}
 @Transactional public WarehouseView createWarehouse(WarehouseRequest r){if(r.code()==null||r.code().isBlank()||r.name()==null||r.name().isBlank())throw new IllegalArgumentException("Warehouse code and name are required");Warehouse w=new Warehouse();w.setTenantId(TENANT);w.setCode(r.code().trim());w.setName(r.name().trim());w.setStatus("ACTIVE");return map(warehouses.save(w));}
 public List<MaterialView> materials(){return materials(defaultWarehouse());} public List<MaterialView> materials(Long warehouseId){validateWarehouse(warehouseId);return materials.findByTenantIdOrderByName(TENANT).stream().map(m->view(m,warehouseId)).toList();}
 @Transactional public MaterialView create(MaterialRequest r){if(r.sku()==null||r.sku().isBlank()||r.name()==null||r.name().isBlank()||r.unit()==null||r.unit().isBlank())throw new IllegalArgumentException("SKU, name and unit are required");String sku=r.sku().trim();if(materials.existsByTenantIdAndSku(TENANT,sku))throw new IllegalArgumentException("Material SKU already exists");Long warehouseId=r.warehouseId()==null?defaultWarehouse():r.warehouseId();validateWarehouse(warehouseId);Material m=new Material();m.setTenantId(TENANT);m.setSku(sku);m.setName(r.name().trim());m.setDescription(r.description());m.setUnit(r.unit().trim().toUpperCase());m.setReorderLevel(r.reorderLevel()==null?BigDecimal.ZERO:r.reorderLevel());if(m.getReorderLevel().signum()<0)throw new IllegalArgumentException("Reorder level cannot be negative");m.setStatus("ACTIVE");m=materials.save(m);if(r.initialQuantity()!=null&&r.initialQuantity().signum()!=0){if(r.initialQuantity().signum()<0)throw new IllegalArgumentException("Initial quantity cannot be negative");addTransaction(m.getId(),warehouseId,"STOCK_IN",r.initialQuantity(),"MATERIAL",m.getId());}return view(m,warehouseId);}
 @Transactional public void stock(Long productId,Long warehouseId,BigDecimal quantity,String type,String reference){if(quantity==null||quantity.signum()<=0)throw new IllegalArgumentException("Quantity must be greater than zero");lockProduct(productId);validate(productId,warehouseId);addTransaction(productId,warehouseId,type,quantity,reference,null);}
 @Transactional public void adjust(Long productId,Long warehouseId,BigDecimal quantity,String reference){if(quantity==null||quantity.signum()==0)throw new IllegalArgumentException("Adjustment cannot be zero");lockProduct(productId);validate(productId,warehouseId);BigDecimal balance=transactions.balance(TENANT,warehouseId,productId);if(balance.add(quantity).signum()<0)throw new IllegalArgumentException("Adjustment would make stock negative");addTransaction(productId,warehouseId,"ADJUSTMENT",quantity,reference,null);}
 @Transactional public DispatchView dispatch(DispatchRequest r){if(r.customerId()==null)throw new IllegalArgumentException("Customer is required");if(r.items()==null||r.items().isEmpty())throw new IllegalArgumentException("At least one dispatch item is required");List<ItemRequest> ordered=new ArrayList<>(r.items());ordered.sort(Comparator.comparing(ItemRequest::productId));Set<Long> locked=new HashSet<>();for(ItemRequest i:ordered){if(i.productId()==null||i.warehouseId()==null||i.quantity()==null||i.quantity().signum()<=0)throw new IllegalArgumentException("Each dispatch item requires a material, warehouse and positive quantity");if(locked.add(i.productId()))lockProduct(i.productId());validate(i.productId(),i.warehouseId());}for(ItemRequest i:ordered){BigDecimal balance=transactions.balance(TENANT,i.warehouseId(),i.productId());if(balance.compareTo(i.quantity())<0)throw new IllegalArgumentException("Insufficient stock for material " + i.productId());}Dispatch d=new Dispatch();d.setTenantId(TENANT);d.setDispatchNumber("DSP-"+UUID.randomUUID().toString().substring(0,8).toUpperCase());d.setCustomerId(r.customerId());d.setReferenceNumber(r.referenceNumber());d.setDeliveryAddress(r.deliveryAddress());d.setNotes(r.notes());d.setDispatchDate(Instant.now());d.setStatus("DISPATCHED");for(ItemRequest i:r.items()){DispatchItem di=new DispatchItem();di.setProductId(i.productId());di.setQuantity(i.quantity());di.setWarehouseId(i.warehouseId());d.addItem(di);}d=dispatches.save(d);for(DispatchItem i:d.getItems())addTransaction(i.getProductId(),i.getWarehouseId(),"DISPATCH",i.getQuantity().negate(),"DISPATCH",d.getId());return view(d);}
 public List<DispatchView> history(){return dispatches.findByTenantIdOrderByDispatchDateDesc(TENANT).stream().map(this::view).toList();} public List<TransactionView> transactions(){return transactions.findTop100ByTenantIdOrderByCreatedAtDesc(TENANT).stream().map(t->new TransactionView(t.getId(),t.getProductId(),t.getWarehouseId(),t.getTransactionType(),t.getQuantity(),t.getReferenceType(),t.getReferenceId(),t.getCorrelationId(),t.getCreatedAt())).toList();}
 private Long defaultWarehouse(){return warehouses.findByTenantIdOrderByName(TENANT).stream().filter(w->"ACTIVE".equals(w.getStatus())).findFirst().map(Warehouse::getId).orElseThrow(()->new IllegalStateException("No active warehouse configured"));} private void validateWarehouse(Long w){warehouses.findByIdAndTenantId(w,TENANT).filter(x->"ACTIVE".equals(x.getStatus())).orElseThrow(()->new NoSuchElementException("Active warehouse not found"));} private void validate(Long p,Long w){materials.findByIdAndTenantId(p,TENANT).orElseThrow(()->new NoSuchElementException("Material not found"));validateWarehouse(w);} private void lockProduct(Long p){materials.findForUpdate(p,TENANT).orElseThrow(()->new NoSuchElementException("Material not found"));}
 private void addTransaction(Long p,Long w,String type,BigDecimal q,String ref,Long refId){InventoryTransaction t=new InventoryTransaction();t.setTenantId(TENANT);t.setProductId(p);t.setWarehouseId(w);t.setTransactionType(type);t.setQuantity(q);t.setReferenceType(ref);t.setReferenceId(refId);t.setCorrelationId(UUID.randomUUID().toString());transactions.save(t);} private MaterialView view(Material m,Long warehouseId){return new MaterialView(m.getId(),m.getSku(),m.getName(),m.getDescription(),m.getUnit(),m.getReorderLevel(),m.getStatus(),transactions.balance(TENANT,warehouseId,m.getId()));} private WarehouseView map(Warehouse w){return new WarehouseView(w.getId(),w.getCode(),w.getName(),w.getStatus());} private DispatchView view(Dispatch d){return new DispatchView(d.getId(),d.getDispatchNumber(),d.getCustomerId(),d.getReferenceNumber(),d.getDispatchDate(),d.getDeliveryAddress(),d.getNotes(),d.getStatus(),d.getItems().stream().map(i->new ItemView(i.getProductId(),i.getWarehouseId(),i.getQuantity())).toList());}
 public record WarehouseRequest(String code,String name){} public record WarehouseView(Long id,String code,String name,String status){} public record MaterialRequest(String sku,String name,String description,String unit,BigDecimal initialQuantity,BigDecimal reorderLevel,Long warehouseId){} public record MaterialView(Long id,String sku,String name,String description,String unit,BigDecimal reorderLevel,String status,BigDecimal quantity){} public record ItemRequest(Long productId,Long warehouseId,BigDecimal quantity){} public record DispatchRequest(Long customerId,String referenceNumber,String deliveryAddress,String notes,List<ItemRequest> items){} public record ItemView(Long productId,Long warehouseId,BigDecimal quantity){} public record DispatchView(Long id,String dispatchNumber,Long customerId,String referenceNumber,Instant dispatchDate,String deliveryAddress,String notes,String status,List<ItemView> items){} public record TransactionView(Long id,Long productId,Long warehouseId,String transactionType,BigDecimal quantity,String referenceType,Long referenceId,String correlationId,Instant createdAt){}
}
