import {Component,OnInit,Input,inject} from '@angular/core';
import {CommonModule} from '@angular/common'; import {FormsModule} from '@angular/forms';
import {HrApi,Employee,Department,Attendance,LeaveRequest,Goal,Payslip,Designation} from './hr-api.service'; import {AuthService} from './auth.service';

@Component({selector:'app-hr',standalone:true,imports:[CommonModule,FormsModule],template:`
<section class="panel">
 <div class="toolbar"><div><h2>People & HR</h2><p>Employees, organization, attendance, leave, payroll and goals.</p></div><div class="hr-actions">
   <button *ngIf="section==='employees'" (click)="openNewEmployee()">+ Staff Login</button>
   <ng-container *ngIf="section==='organization'"><div class="hr-actions"><button (click)="openNewDepartment()">+ Department</button><button (click)="openNewDesignation()">+ Designation</button></div></ng-container>
 </div></div>
 <div class="cards"><article><span>Employees</span><strong>{{employees.length}}</strong><small>People in tenant</small></article><article><span>Departments</span><strong>{{departments.length}}</strong><small>Organization units</small></article><article><span>Pending leave</span><strong>{{pendingLeaves}}</strong><small>Requests awaiting action</small></article><article><span>Payslips</span><strong>{{payslips.length}}</strong><small>Employee payroll records</small></article></div>

 <div *ngIf="section==='employees'"><div class="toolbar"><div><h2>Employee & staff accounts</h2><p>Create, edit, enable/disable and reset employee logins. Passwords are sent only to Keycloak and never stored in Sivion.</p></div></div>
 <table><thead><tr><th>Number</th><th>Name</th><th>Username</th><th>Department</th><th>Designation</th><th>Role</th><th>Account</th><th>Actions</th></tr></thead><tbody>
 <tr *ngFor="let e of employees"><td>{{e.employeeNumber}}</td><td><b>{{e.firstName}} {{e.lastName}}</b><br><small>{{e.email}}</small></td><td>{{e.username||'—'}}</td><td>{{departmentName(e.departmentId)}}</td><td>{{e.designation||'—'}}</td><td>{{e.role||'EMPLOYEE'}}</td><td><span class="pill" [class.inactive-pill]="!e.accountEnabled">{{e.accountEnabled?'Enabled':'Disabled'}}</span></td><td><button type="button" (click)="openEditEmployee(e)">Manage</button></td></tr>
 <tr *ngIf="!employees.length"><td colspan="8" class="empty">No employees configured.</td></tr></tbody></table></div>

 <div *ngIf="section==='organization'"><div class="toolbar"><div><h2>Organization structure</h2><p>Manage departments, designations and their reporting hierarchy.</p></div></div>
 <table><thead><tr><th>Code</th><th>Department</th><th>Parent</th><th>Status</th><th>Employees</th><th>Actions</th></tr></thead><tbody><tr *ngFor="let d of departments"><td>{{d.code}}</td><td><b>{{d.name}}</b></td><td>{{departmentName(d.parentId)}}</td><td><span class="pill">{{d.status||'ACTIVE'}}</span></td><td>{{employeesInDepartment(d.id)}}</td><td><button type="button" (click)="openEditDepartment(d)">Edit</button></td></tr><tr *ngIf="departments.length===0"><td colspan="6">No departments configured yet.</td></tr></tbody></table><div class="toolbar sub"><h3>Designations</h3><button *ngIf="canModifyHr" (click)="openNewDesignation()">+ Designation</button></div><table><thead><tr><th>Code</th><th>Designation</th><th>Status</th><th>Actions</th></tr></thead><tbody><tr *ngFor="let d of designations"><td>{{d.code}}</td><td><b>{{d.name}}</b></td><td><span class="pill">{{d.status||'ACTIVE'}}</span></td><td><button *ngIf="canModifyHr" (click)="openEditDesignation(d)">Edit</button></td></tr></tbody></table></div>

 <div *ngIf="section==='attendance'"><div class="toolbar"><h2>Attendance</h2></div><table><thead><tr><th>Date</th><th>Employee</th><th>Status</th><th>Check in</th><th>Check out</th></tr></thead><tbody><tr *ngFor="let a of attendance"><td>{{a.attendanceDate}}</td><td>{{employeeName(a.employeeId)}}</td><td>{{a.status}}</td><td>{{a.checkIn||'—'}}</td><td>{{a.checkOut||'—'}}</td></tr></tbody></table></div>

 <div *ngIf="section==='leaves'"><div class="toolbar"><div><h2>Leave management</h2><p>HR and administrators can review and modify employee leave requests.</p></div></div><table><thead><tr><th>Employee</th><th>Type</th><th>Dates</th><th>Reason</th><th>Status</th><th>Action</th></tr></thead><tbody><tr *ngFor="let l of leaves"><td>{{employeeName(l.employeeId)}}</td><td>{{l.leaveType}}</td><td>{{l.startDate}} → {{l.endDate}}</td><td>{{l.reason||'—'}}</td><td><span class="pill">{{l.status}}</span></td><td><button *ngIf="l.status==='PENDING'" (click)="updateLeave(l,'APPROVED')">Approve</button><button *ngIf="l.status==='PENDING'" (click)="updateLeave(l,'REJECTED')">Reject</button></td></tr></tbody></table></div>

 <div *ngIf="section==='payroll'"><div class="toolbar"><div><h2>Payroll & payslips</h2><p>HR can create and modify employee pay records. Admin has the same full access.</p></div><button *ngIf="canModifyHr" (click)="openNewPayslip()">+ Payslip</button></div>
 <table><thead><tr><th>Employee</th><th>Period</th><th>Gross</th><th>Deductions</th><th>Net</th><th>Status</th><th>Actions</th></tr></thead><tbody>
 <tr *ngFor="let p of payslips"><td>{{employeeName(p.employeeId)}}</td><td>{{p.periodStart}} → {{p.periodEnd}}</td><td>₹{{p.grossPay|number:'1.2-2'}}</td><td>₹{{p.deductions|number:'1.2-2'}}</td><td>₹{{(p.netPay ?? (p.grossPay-p.deductions))|number:'1.2-2'}}</td><td><span class="pill">{{p.status}}</span></td><td><button *ngIf="canModifyHr" (click)="openEditPayslip(p)">Edit</button></td></tr>
 <tr *ngIf="!payslips.length"><td colspan="7" class="empty">No payslips configured.</td></tr></tbody></table></div>

 <div *ngIf="section==='goals'"><div class="toolbar"><h2>Goals</h2></div><table><thead><tr><th>Employee</th><th>Goal</th><th>Progress</th><th>Due</th></tr></thead><tbody><tr *ngFor="let g of goals"><td>{{employeeName(g.employeeId)}}</td><td><b>{{g.title}}</b><br><small>{{g.description}}</small></td><td>{{g.currentValue||0}} / {{g.targetValue||0}}</td><td>{{g.dueDate||'—'}}</td></tr></tbody></table></div>

 <div *ngIf="section==='reports'" class="feature-list"><div><strong>Workforce</strong><span>{{activeEmployees}} active employees across {{departments.length}} departments.</span></div><div><strong>Leave</strong><span>{{pendingLeaves}} leave requests require action.</span></div><div><strong>Payroll</strong><span>{{payslips.length}} payslips are available to HR.</span></div></div>
 <div *ngIf="['holidays','meetings','performance','knowledge','documents'].includes(section)" class="feature-list"><div><strong>{{sectionTitle}}</strong><span>This HR section is wired into the role-aware workspace and is ready for its dedicated lifecycle.</span></div></div>

 <div *ngIf="employeeModal" class="modal"><form (ngSubmit)="saveEmployee()"><h2>{{editingEmployee?'Manage staff login':'Create staff login'}}</h2><p class="hint">The password is used only for Keycloak account creation/reset and is never returned by the API.</p><p *ngIf="formError" class="form-error" role="alert">{{formError}}</p>
 <input required maxlength="40" placeholder="Employee number" [(ngModel)]="employeeDraft.employeeNumber" name="number"><input required placeholder="First name" [(ngModel)]="employeeDraft.firstName" name="first"><input required placeholder="Last name" [(ngModel)]="employeeDraft.lastName" name="last"><input required type="email" placeholder="Email" [(ngModel)]="employeeDraft.email" name="email"><input placeholder="Phone" [(ngModel)]="employeeDraft.phone" name="phone">
 <select [(ngModel)]="employeeDraft.departmentId" name="department"><option [ngValue]="undefined">No department</option><option *ngFor="let d of departments" [ngValue]="d.id">{{d.name}}</option></select><select [(ngModel)]="employeeDraft.designationId" name="designation"><option [ngValue]="undefined">No designation</option><option *ngFor="let d of designations" [ngValue]="d.id">{{d.name}}</option></select>
 <div class="form-grid"><input required placeholder="Username" [(ngModel)]="employeeDraft.username" name="username"><select [(ngModel)]="employeeDraft.role" name="role"><option *ngFor="let role of availableRoles" [value]="role">{{role}}</option></select></div>
 <input type="password" [required]="!editingEmployee" minlength="8" placeholder="{{editingEmployee?'New password (leave blank to keep current)':'Initial password'}}" [(ngModel)]="employeeDraft.password" name="password"><label class="check"><input type="checkbox" [(ngModel)]="employeeDraft.temporaryPassword" name="temporary"> Force password change at first login</label><label class="check"><input type="checkbox" [(ngModel)]="employeeDraft.accountEnabled" name="enabled"> Login enabled</label>
 <div class="actions"><button type="button" (click)="closeEmployeeModal()">Cancel</button><button type="submit">{{editingEmployee?'Save changes':'Create staff & login'}}</button></div></form></div>

 <div *ngIf="departmentModal" class="modal"><form (ngSubmit)="saveDepartment()"><h2>{{editingDepartment ? 'Edit department' : 'New department'}}</h2><p *ngIf="formError" class="form-error" role="alert">{{formError}}</p><input required maxlength="40" placeholder="Department code" [(ngModel)]="departmentDraft.code" name="code"><input required maxlength="160" placeholder="Department name" [(ngModel)]="departmentDraft.name" name="name"><select [(ngModel)]="departmentDraft.parentId" name="parent"><option [ngValue]="undefined">No parent</option><option *ngFor="let d of availableParents" [ngValue]="d.id">{{d.name}}</option></select><select [(ngModel)]="departmentDraft.status" name="status"><option value="ACTIVE">Active</option><option value="INACTIVE">Inactive</option></select><div class="actions"><button type="button" (click)="closeDepartmentModal()">Cancel</button><button type="submit">{{editingDepartment ? 'Save changes' : 'Create'}}</button></div></form></div>

 <div *ngIf="designationModal" class="modal"><form (ngSubmit)="saveDesignation()"><h2>{{editingDesignation?'Edit designation':'New designation'}}</h2><p *ngIf="formError" class="form-error" role="alert">{{formError}}</p><input required maxlength="40" placeholder="Designation code" [(ngModel)]="designationDraft.code" name="designationCode"><input required maxlength="160" placeholder="Designation name" [(ngModel)]="designationDraft.name" name="designationName"><select [(ngModel)]="designationDraft.status" name="designationStatus"><option value="ACTIVE">Active</option><option value="INACTIVE">Inactive</option></select><div class="actions"><button type="button" (click)="closeDesignationModal()">Cancel</button><button type="submit">Save designation</button></div></form></div>

 <div *ngIf="payslipModal" class="modal"><form (ngSubmit)="savePayslip()"><h2>{{editingPayslip?'Edit payslip':'New payslip'}}</h2><p *ngIf="formError" class="form-error" role="alert">{{formError}}</p><select required [(ngModel)]="payslipDraft.employeeId" name="employee"><option [ngValue]="0">Select employee</option><option *ngFor="let e of employees" [ngValue]="e.id">{{e.employeeNumber}} — {{e.firstName}} {{e.lastName}}</option></select><div class="form-grid"><input required type="date" [(ngModel)]="payslipDraft.periodStart" name="periodStart"><input required type="date" [(ngModel)]="payslipDraft.periodEnd" name="periodEnd"></div><div class="form-grid"><input required type="number" min="0" step="0.01" placeholder="Gross pay" [(ngModel)]="payslipDraft.grossPay" name="gross"><input required type="number" min="0" step="0.01" placeholder="Deductions" [(ngModel)]="payslipDraft.deductions" name="deductions"></div><input type="number" min="0" step="0.01" placeholder="Net pay (optional; auto calculated)" [(ngModel)]="payslipDraft.netPay" name="net"><select [(ngModel)]="payslipDraft.status" name="status"><option>DRAFT</option><option>PROCESSED</option><option>PAID</option></select><textarea placeholder="Notes" [(ngModel)]="payslipDraft.notes" name="notes"></textarea><div class="actions"><button type="button" (click)="closePayslipModal()">Cancel</button><button type="submit">Save payslip</button></div></form></div>
</section>`,styles:[`
:host .hr-actions{display:flex;align-items:center;gap:1vw}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.hint{font-size:12px;color:#667085;margin:0}.form-error{margin:0;padding:8px 10px;border-radius:6px;background:#fef3f2;color:#b42318}.check{display:flex;align-items:center;gap:8px;font-size:13px}.check input{width:auto}.inactive-pill{background:#f2f4f7;color:#667085}textarea{width:100%;min-height:90px;border:1px solid #d0d5dd;border-radius:8px;padding:11px 12px;font:inherit}
`]})
export class HrComponent implements OnInit {
 @Input() section='employees'; api=inject(HrApi); auth=inject(AuthService);
 employees:Employee[]=[]; departments:Department[]=[]; designations:Designation[]=[]; attendance:Attendance[]=[]; leaves:LeaveRequest[]=[]; goals:Goal[]=[]; payslips:Payslip[]=[];
 employeeModal=false; editingEmployee=false; departmentModal=false; editingDepartment=false; payslipModal=false; editingPayslip=false; designationModal=false; editingDesignation=false; formError='';
 employeeDraft:Employee=this.emptyEmployee(); departmentDraft:Department={code:'',name:'',status:'ACTIVE'}; designationDraft:Designation={code:'',name:'',status:'ACTIVE'}; payslipDraft:Payslip=this.emptyPayslip();
 async ngOnInit(){await this.reload();}
 get canModifyHr(){return this.auth.hasRole('ADMIN')||this.auth.hasRole('HR_ADMIN')||this.auth.hasRole('HR_USER');}
 get isAdmin(){return this.auth.hasRole('ADMIN');}
 get availableRoles(){return this.isAdmin?['ADMIN','HR_ADMIN','HR_USER','MANAGER','EMPLOYEE','SALES_MANAGER','SALES_USER','INVENTORY_MANAGER','INVENTORY_USER','WAREHOUSE_MANAGER','WAREHOUSE_USER','PROCUREMENT_MANAGER','FINANCE_MANAGER','FINANCE_USER','MARKETING_USER']:['HR_USER','MANAGER','EMPLOYEE'];}
 async reload(){[this.employees,this.departments,this.designations,this.attendance,this.leaves,this.goals,this.payslips]=await Promise.all([this.api.employees(),this.api.departments(),this.api.designations(),this.api.attendance(),this.api.leaves(),this.api.goals(),this.api.payslips()]);}
 get pendingLeaves(){return this.leaves.filter(x=>x.status==='PENDING').length;} get activeEmployees(){return this.employees.filter(x=>x.status==='ACTIVE').length;} get sectionTitle(){return this.section[0].toUpperCase()+this.section.slice(1);}
 get availableParents(){const currentId=this.departmentDraft.id;return this.departments.filter(d=>d.id!==currentId);}
 departmentName(id?:number){return id?this.departments.find(x=>x.id===id)?.name||`Department #${id}`:'—';}
 employeeName(id:number){const e=this.employees.find(x=>x.id===id);return e?`${e.firstName} ${e.lastName}`:`Employee #${id}`;}
 employeesInDepartment(id?:number){return this.employees.filter(x=>x.departmentId===id).length;}
 openNewEmployee(){this.employeeDraft=this.emptyEmployee();this.employeeModal=true;this.formError='';}
 openEditEmployee(e:Employee){this.employeeDraft={...e,password:'',temporaryPassword:false};this.editingEmployee=true;this.employeeModal=true;this.formError='';}
 closeEmployeeModal(){this.employeeModal=false;this.editingEmployee=false;this.formError='';}
 async saveEmployee(){this.formError='';try{if(this.editingEmployee&&this.employeeDraft.id){await this.api.updateEmployee(this.employeeDraft.id,this.employeeDraft);}else{await this.api.createEmployee(this.employeeDraft);}this.closeEmployeeModal();await this.reload();}catch(e:any){this.formError=e?.error?.error||e?.message||'Unable to save staff account.';}}
 openNewDepartment(){this.departmentDraft={code:'',name:'',status:'ACTIVE'};this.editingDepartment=false;this.formError='';this.departmentModal=true;}
 openEditDepartment(d:Department){this.departmentDraft={...d};this.editingDepartment=true;this.formError='';this.departmentModal=true;}
 closeDepartmentModal(){this.departmentModal=false;this.editingDepartment=false;this.formError='';}
 async saveDepartment(){this.formError='';try{if(this.editingDepartment){await this.api.updateDepartment(this.departmentDraft);}else{await this.api.createDepartment(this.departmentDraft);}this.closeDepartmentModal();await this.reload();}catch(e:any){this.formError=e?.error?.error||e?.message||'Unable to save department.';}}
 async updateLeave(l:LeaveRequest,status:string){if(l.id){try{await this.api.updateLeave(l.id,status);await this.reload();}catch(e:any){this.formError='Unable to update leave request.';}}}
 openNewDesignation(){this.designationDraft={code:'',name:'',status:'ACTIVE'};this.editingDesignation=false;this.designationModal=true;this.formError='';}
 openEditDesignation(d:Designation){this.designationDraft={...d};this.editingDesignation=true;this.designationModal=true;this.formError='';}
 closeDesignationModal(){this.designationModal=false;this.editingDesignation=false;this.formError='';}
 async saveDesignation(){this.formError='';try{if(this.editingDesignation&&this.designationDraft.id)await this.api.updateDesignation(this.designationDraft);else await this.api.createDesignation(this.designationDraft);this.closeDesignationModal();await this.reload();}catch(e:any){this.formError=e?.error?.error||e?.message||'Unable to save designation.';}}
 openNewPayslip(){this.payslipDraft=this.emptyPayslip();this.payslipModal=true;this.editingPayslip=false;this.formError='';}
 openEditPayslip(p:Payslip){this.payslipDraft={...p};this.payslipModal=true;this.editingPayslip=true;this.formError='';}
 closePayslipModal(){this.payslipModal=false;this.editingPayslip=false;this.formError='';}
 async savePayslip(){this.formError='';try{if(this.editingPayslip&&this.payslipDraft.id)await this.api.updatePayslip(this.payslipDraft.id,this.payslipDraft);else await this.api.createPayslip(this.payslipDraft);this.closePayslipModal();await this.reload();}catch(e:any){this.formError=e?.error?.error||e?.message||'Unable to save payslip.';}}
 private emptyEmployee():Employee{return{employeeNumber:'',firstName:'',lastName:'',email:'',status:'ACTIVE',role:'EMPLOYEE',accountEnabled:true,temporaryPassword:false,password:''};}
 private emptyPayslip():Payslip{return{employeeId:0,periodStart:'',periodEnd:'',grossPay:0,deductions:0,status:'DRAFT'};}
}
