package com.sivion.api.hr;

import com.sivion.api.hr.domain.*; import com.sivion.api.hr.repository.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.*; import java.util.*;
@Service @Transactional
public class HrService {
 private static final Long TENANT_ID=1L;
 private final EmployeeRepository employees; private final DepartmentRepository departments; private final DesignationRepository designations; private final AttendanceRepository attendance; private final LeaveRequestRepository leaves; private final GoalRepository goals;
 public HrService(EmployeeRepository e,DepartmentRepository d,DesignationRepository ds,AttendanceRepository a,LeaveRequestRepository l,GoalRepository g){employees=e;departments=d;designations=ds;attendance=a;leaves=l;goals=g;}
 public List<Employee> employees(){return employees.findByTenantIdOrderByLastNameAscFirstNameAsc(TENANT_ID);} public List<Department> departments(){return departments.findByTenantIdOrderByName(TENANT_ID);} public long activeEmployees(){return employees.countByTenantIdAndStatus(TENANT_ID,"ACTIVE");}
 public Employee createEmployee(Employee e){e.setTenantId(TENANT_ID); if(e.getStatus()==null)e.setStatus("ACTIVE"); return employees.save(e);}
 public List<Designation> designations(){return designations.findByTenantIdOrderByName(TENANT_ID);}
 public Designation createDesignation(Designation d){normalizeDesignation(d); d.setTenantId(TENANT_ID); validateDesignation(d,null); return designations.save(d);}
 public Designation updateDesignation(Long id,Designation input){Designation current=designations.findById(id).orElseThrow(()->new IllegalArgumentException("Designation not found")); if(!TENANT_ID.equals(current.getTenantId()))throw new IllegalArgumentException("Designation not found"); normalizeDesignation(input); current.setCode(input.getCode()); current.setName(input.getName()); current.setDescription(input.getDescription()); current.setDepartmentId(input.getDepartmentId()); current.setStatus(input.getStatus()); validateDesignation(current,id); return designations.save(current);}
 private void normalizeDesignation(Designation d){if(d.getCode()!=null)d.setCode(d.getCode().trim().toUpperCase(Locale.ROOT));if(d.getName()!=null)d.setName(d.getName().trim());if(d.getDescription()!=null)d.setDescription(d.getDescription().trim());if(d.getStatus()==null||d.getStatus().isBlank())d.setStatus("ACTIVE");else d.setStatus(d.getStatus().trim().toUpperCase(Locale.ROOT));}
 private void validateDesignation(Designation d,Long currentId){if(d.getCode()==null||d.getCode().isBlank())throw new IllegalArgumentException("Designation code is required");if(d.getName()==null||d.getName().isBlank())throw new IllegalArgumentException("Designation name is required");if(!d.getStatus().equals("ACTIVE")&&!d.getStatus().equals("INACTIVE"))throw new IllegalArgumentException("Designation status must be ACTIVE or INACTIVE");if(currentId==null?designations.existsByTenantIdAndCode(TENANT_ID,d.getCode()):designations.existsByTenantIdAndCodeAndIdNot(TENANT_ID,d.getCode(),currentId))throw new IllegalArgumentException("Designation code already exists");if(d.getDepartmentId()!=null){Department department=departments.findById(d.getDepartmentId()).orElseThrow(()->new IllegalArgumentException("Department not found"));if(!TENANT_ID.equals(department.getTenantId()))throw new IllegalArgumentException("Invalid department");}}
 public Department createDepartment(Department d){normalizeDepartment(d); d.setTenantId(TENANT_ID); validateDepartment(d,null); return departments.save(d);}
 public Department updateDepartment(Long id,Department input){Department current=departments.findById(id).orElseThrow(()->new IllegalArgumentException("Department not found")); if(!TENANT_ID.equals(current.getTenantId()))throw new IllegalArgumentException("Department not found"); normalizeDepartment(input); current.setCode(input.getCode()); current.setName(input.getName()); current.setParentId(input.getParentId()); current.setStatus(input.getStatus()); validateDepartment(current,id); return departments.save(current);}
 private void normalizeDepartment(Department d){if(d.getCode()!=null)d.setCode(d.getCode().trim().toUpperCase(Locale.ROOT));if(d.getName()!=null)d.setName(d.getName().trim());if(d.getStatus()==null||d.getStatus().isBlank())d.setStatus("ACTIVE");else d.setStatus(d.getStatus().trim().toUpperCase(Locale.ROOT));}
 private void validateDepartment(Department d,Long currentId){if(d.getCode()==null||d.getCode().isBlank())throw new IllegalArgumentException("Department code is required");if(d.getName()==null||d.getName().isBlank())throw new IllegalArgumentException("Department name is required");if(!d.getStatus().equals("ACTIVE")&&!d.getStatus().equals("INACTIVE"))throw new IllegalArgumentException("Department status must be ACTIVE or INACTIVE");if(currentId==null?departments.existsByTenantIdAndCode(TENANT_ID,d.getCode()):departments.existsByTenantIdAndCodeAndIdNot(TENANT_ID,d.getCode(),currentId))throw new IllegalArgumentException("Department code already exists");if(d.getParentId()!=null){Department parent=departments.findById(d.getParentId()).orElseThrow(()->new IllegalArgumentException("Parent department not found"));if(!TENANT_ID.equals(parent.getTenantId()))throw new IllegalArgumentException("Invalid parent department");if(currentId!=null&&currentId.equals(parent.getId()))throw new IllegalArgumentException("A department cannot be its own parent");if(currentId!=null){Long ancestor=parent.getParentId();while(ancestor!=null){if(currentId.equals(ancestor))throw new IllegalArgumentException("Department hierarchy cannot contain cycles");Department next=departments.findById(ancestor).orElseThrow(()->new IllegalArgumentException("Invalid parent hierarchy"));if(!TENANT_ID.equals(next.getTenantId()))throw new IllegalArgumentException("Invalid parent hierarchy");ancestor=next.getParentId();}}}}
 public Attendance markAttendance(Attendance a){a.setTenantId(TENANT_ID); return attendance.findByTenantIdAndEmployeeIdAndAttendanceDate(TENANT_ID,a.getEmployeeId(),a.getAttendanceDate()).map(x->{x.setStatus(a.getStatus());x.setCheckIn(a.getCheckIn());x.setCheckOut(a.getCheckOut());return attendance.save(x);}).orElseGet(()->attendance.save(a));}
 public List<Attendance> attendance(LocalDate from,LocalDate to){return attendance.findByTenantIdAndAttendanceDateBetweenOrderByAttendanceDateDesc(TENANT_ID,from,to);} public List<LeaveRequest> leaves(){return leaves.findByTenantIdOrderByCreatedAtDesc(TENANT_ID);} public LeaveRequest requestLeave(LeaveRequest l){l.setTenantId(TENANT_ID);l.setStatus("PENDING");return leaves.save(l);}
 public LeaveRequest updateLeave(Long id,String status,Long approver){LeaveRequest l=leaves.findById(id).orElseThrow(()->new IllegalArgumentException("Leave request not found"));if(!l.getTenantId().equals(TENANT_ID))throw new IllegalArgumentException("Invalid tenant");l.setStatus(status);l.setApprovedBy(approver);return leaves.save(l);}
 public List<Goal> goals(){return goals.findByTenantIdOrderByDueDateAsc(TENANT_ID);} public Goal createGoal(Goal g){g.setTenantId(TENANT_ID);return goals.save(g);}
}
